# Stage 1: Install dependencies
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
RUN npm install -g pnpm@10.18.2

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY packages/pricing/package.json ./packages/pricing/
COPY frontend/package.json ./frontend/

RUN pnpm install --frozen-lockfile

# Stage 2: Build the Next.js frontend
FROM node:20-alpine AS builder
WORKDIR /app
RUN npm install -g pnpm@10.18.2

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/frontend/node_modules ./frontend/node_modules

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY packages/pricing ./packages/pricing
COPY frontend ./frontend
COPY content ./content
COPY scripts ./scripts
COPY fixtures ./fixtures
COPY docs/model-roster.json ./docs/model-roster.json
COPY docs/model-roster.csv ./docs/model-roster.csv
COPY data ./data

ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_SKIP_ESLINT=1

# Next.js build-time environment variables
ARG NEXT_PUBLIC_API_BASE
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_ASSET_MAX_IMAGE_DIMENSION
ARG NEXT_PUBLIC_ASSET_MAX_IMAGE_MB
ARG NEXT_PUBLIC_ASSET_UPLOAD_TARGET_MB
ARG NEXT_PUBLIC_BING_VERIFY
ARG NEXT_PUBLIC_CLARITY_ALLOWED_HOSTS
ARG NEXT_PUBLIC_CLARITY_DEBUG
ARG NEXT_PUBLIC_CLARITY_ID
ARG NEXT_PUBLIC_COOKIE_DOMAIN
ARG NEXT_PUBLIC_DEFAULT_RESULT_PROVIDER
ARG NEXT_PUBLIC_DISABLE_GA
ARG NEXT_PUBLIC_DISABLE_GTM
ARG NEXT_PUBLIC_ENABLE_CLARITY
ARG NEXT_PUBLIC_ENABLE_SEARCH_SCHEMA
ARG NEXT_PUBLIC_ENABLE_THUMBNAILS
ARG NEXT_PUBLIC_FAL_FILES_BASE_URL
ARG NEXT_PUBLIC_FEATURE_LAUNCH_TIMESTAMP
ARG NEXT_PUBLIC_GA4_ID
ARG NEXT_PUBLIC_GA_ID
ARG NEXT_PUBLIC_GOOGLE_ADS_CONVERSION_CURRENCY
ARG NEXT_PUBLIC_GOOGLE_ADS_CONVERSION_ID
ARG NEXT_PUBLIC_GOOGLE_ADS_CONVERSION_VALUE
ARG NEXT_PUBLIC_GOOGLE_ADS_ID
ARG NEXT_PUBLIC_GOOGLE_ANALYTICS_ID
ARG NEXT_PUBLIC_GOOGLE_CONSENT_MODE
ARG NEXT_PUBLIC_GTM_ID
ARG NEXT_PUBLIC_LEGAL_MIN_AGE
ARG NEXT_PUBLIC_RESULT_PROVIDER
ARG NEXT_PUBLIC_SERVICE_NOTICE
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_TURNSTILE_SITE_KEY
ARG NEXT_PUBLIC_VISITOR_WORKSPACE_ACCESS
ARG NEXT_PUBLIC_WORKSPACE_CENTER_GALLERY

ENV NEXT_PUBLIC_API_BASE=$NEXT_PUBLIC_API_BASE
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_ASSET_MAX_IMAGE_DIMENSION=$NEXT_PUBLIC_ASSET_MAX_IMAGE_DIMENSION
ENV NEXT_PUBLIC_ASSET_MAX_IMAGE_MB=$NEXT_PUBLIC_ASSET_MAX_IMAGE_MB
ENV NEXT_PUBLIC_ASSET_UPLOAD_TARGET_MB=$NEXT_PUBLIC_ASSET_UPLOAD_TARGET_MB
ENV NEXT_PUBLIC_BING_VERIFY=$NEXT_PUBLIC_BING_VERIFY
ENV NEXT_PUBLIC_CLARITY_ALLOWED_HOSTS=$NEXT_PUBLIC_CLARITY_ALLOWED_HOSTS
ENV NEXT_PUBLIC_CLARITY_DEBUG=$NEXT_PUBLIC_CLARITY_DEBUG
ENV NEXT_PUBLIC_CLARITY_ID=$NEXT_PUBLIC_CLARITY_ID
ENV NEXT_PUBLIC_COOKIE_DOMAIN=$NEXT_PUBLIC_COOKIE_DOMAIN
ENV NEXT_PUBLIC_DEFAULT_RESULT_PROVIDER=$NEXT_PUBLIC_DEFAULT_RESULT_PROVIDER
ENV NEXT_PUBLIC_DISABLE_GA=$NEXT_PUBLIC_DISABLE_GA
ENV NEXT_PUBLIC_DISABLE_GTM=$NEXT_PUBLIC_DISABLE_GTM
ENV NEXT_PUBLIC_ENABLE_CLARITY=$NEXT_PUBLIC_ENABLE_CLARITY
ENV NEXT_PUBLIC_ENABLE_SEARCH_SCHEMA=$NEXT_PUBLIC_ENABLE_SEARCH_SCHEMA
ENV NEXT_PUBLIC_ENABLE_THUMBNAILS=$NEXT_PUBLIC_ENABLE_THUMBNAILS
ENV NEXT_PUBLIC_FAL_FILES_BASE_URL=$NEXT_PUBLIC_FAL_FILES_BASE_URL
ENV NEXT_PUBLIC_FEATURE_LAUNCH_TIMESTAMP=$NEXT_PUBLIC_FEATURE_LAUNCH_TIMESTAMP
ENV NEXT_PUBLIC_GA4_ID=$NEXT_PUBLIC_GA4_ID
ENV NEXT_PUBLIC_GA_ID=$NEXT_PUBLIC_GA_ID
ENV NEXT_PUBLIC_GOOGLE_ADS_CONVERSION_CURRENCY=$NEXT_PUBLIC_GOOGLE_ADS_CONVERSION_CURRENCY
ENV NEXT_PUBLIC_GOOGLE_ADS_CONVERSION_ID=$NEXT_PUBLIC_GOOGLE_ADS_CONVERSION_ID
ENV NEXT_PUBLIC_GOOGLE_ADS_CONVERSION_VALUE=$NEXT_PUBLIC_GOOGLE_ADS_CONVERSION_VALUE
ENV NEXT_PUBLIC_GOOGLE_ADS_ID=$NEXT_PUBLIC_GOOGLE_ADS_ID
ENV NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=$NEXT_PUBLIC_GOOGLE_ANALYTICS_ID
ENV NEXT_PUBLIC_GOOGLE_CONSENT_MODE=$NEXT_PUBLIC_GOOGLE_CONSENT_MODE
ENV NEXT_PUBLIC_GTM_ID=$NEXT_PUBLIC_GTM_ID
ENV NEXT_PUBLIC_LEGAL_MIN_AGE=$NEXT_PUBLIC_LEGAL_MIN_AGE
ENV NEXT_PUBLIC_RESULT_PROVIDER=$NEXT_PUBLIC_RESULT_PROVIDER
ENV NEXT_PUBLIC_SERVICE_NOTICE=$NEXT_PUBLIC_SERVICE_NOTICE
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_TURNSTILE_SITE_KEY=$NEXT_PUBLIC_TURNSTILE_SITE_KEY
ENV NEXT_PUBLIC_VISITOR_WORKSPACE_ACCESS=$NEXT_PUBLIC_VISITOR_WORKSPACE_ACCESS
ENV NEXT_PUBLIC_WORKSPACE_CENTER_GALLERY=$NEXT_PUBLIC_WORKSPACE_CENTER_GALLERY

RUN pnpm --prefix frontend run build

# Stage 3: Runtime runner
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
RUN apk add --no-cache libc6-compat

# Install sharp directly in runner to bypass Next.js standalone tracing exclusions
RUN npm install sharp@0.34.5

# Copy Next.js standalone server outputs
COPY --from=builder --chown=nextjs:nodejs /app/frontend/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/frontend/.next/static ./frontend/.next/static
COPY --from=builder --chown=nextjs:nodejs /app/frontend/public ./frontend/public

# Health check using wget (pre-installed in Alpine)
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/ || exit 1

USER nextjs

EXPOSE 3000

CMD ["node", "frontend/server.js"]
