import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

const root = process.cwd();
const executorPath = join(root, 'frontend/src/server/images/execute-image-generation.ts');
const existingJobResponsePath = join(root, 'frontend/src/server/images/existing-image-job-response.ts');
const referenceNormalizationPath = join(root, 'frontend/src/server/images/image-reference-normalization.ts');
const requestContextPath = join(root, 'frontend/src/server/images/image-generation-request-context.ts');
const referencesPath = join(root, 'frontend/src/server/images/image-generation-references.ts');
const storyboardTemplateReferencePath = join(root, 'frontend/src/server/images/storyboard-template-reference.ts');
const storyboardPricingPath = join(root, 'frontend/src/lib/storyboard-pricing.ts');
const storyboardImageBillingPath = join(root, 'frontend/src/server/images/storyboard-image-billing.ts');
const imageGenerateRoutePath = join(root, 'frontend/app/api/images/generate/route.ts');
const initialJobPath = join(root, 'frontend/src/server/images/image-initial-job.ts');
const errorPath = join(root, 'frontend/src/server/images/image-generation-error.ts');
const providerPayloadPath = join(root, 'frontend/src/server/images/image-provider-payload.ts');
const directProviderExecutionPath = join(root, 'frontend/src/server/images/image-direct-provider-execution.ts');
const bytePlusSeedreamExecutionPath = join(root, 'frontend/src/server/images/byteplus-seedream-execution.ts');
const bytePlusSeedreamPayloadPath = join(root, 'frontend/src/server/images/byteplus-seedream-payload.ts');
const bytePlusSeedreamClientPath = join(root, 'frontend/src/server/images/byteplus-seedream-client.ts');
const bytePlusSeedreamResponsePath = join(root, 'frontend/src/server/images/byteplus-seedream-response.ts');
const lumaAgentsImageExecutionPath = join(root, 'frontend/src/server/images/luma-agents-execution.ts');
const lumaAgentsImagePayloadPath = join(root, 'frontend/src/server/images/luma-agents-payload.ts');
const lumaAgentsImageClientPath = join(root, 'frontend/src/server/images/luma-agents-client.ts');
const lumaAgentsImageResponsePath = join(root, 'frontend/src/server/images/luma-agents-response.ts');
const lumaAgentsImageErrorPath = join(root, 'frontend/src/server/images/luma-agents-error.ts');
const completionPath = join(root, 'frontend/src/server/images/image-generation-completion.ts');
const failurePath = join(root, 'frontend/src/server/images/image-generation-failure.ts');
const receiptsPath = join(root, 'frontend/src/server/images/image-generation-receipts.ts');
const settingsSnapshotPath = join(root, 'frontend/src/server/images/image-generation-settings-snapshot.ts');
const outputStoragePath = join(root, 'frontend/src/server/images/image-output-storage.ts');
const imageGenerationTypesPath = join(root, 'frontend/types/image-generation.ts');
const imageWorkspacePath = join(root, 'frontend/app/(core)/(workspace)/app/image/ImageWorkspace.tsx');
const imageGenerationRunnerPath = join(root, 'frontend/app/(core)/(workspace)/app/image/_hooks/useImageGenerationRunner.ts');

const executorSource = readFileSync(executorPath, 'utf8');
const existingJobResponseSource = readFileSync(existingJobResponsePath, 'utf8');
const referenceNormalizationSource = readFileSync(referenceNormalizationPath, 'utf8');
const requestContextSource = readFileSync(requestContextPath, 'utf8');
const referencesSource = readFileSync(referencesPath, 'utf8');
const storyboardTemplateReferenceSource = readFileSync(storyboardTemplateReferencePath, 'utf8');
const storyboardPricingSource = readFileSync(storyboardPricingPath, 'utf8');
const storyboardImageBillingSource = readFileSync(storyboardImageBillingPath, 'utf8');
const imageGenerateRouteSource = readFileSync(imageGenerateRoutePath, 'utf8');
const initialJobSource = readFileSync(initialJobPath, 'utf8');
const errorSource = readFileSync(errorPath, 'utf8');
const providerPayloadSource = readFileSync(providerPayloadPath, 'utf8');
const directProviderExecutionSource = readFileSync(directProviderExecutionPath, 'utf8');
const bytePlusSeedreamExecutionSource = readFileSync(bytePlusSeedreamExecutionPath, 'utf8');
const lumaAgentsImageExecutionSource = readFileSync(lumaAgentsImageExecutionPath, 'utf8');
const lumaAgentsImagePayloadSource = readFileSync(lumaAgentsImagePayloadPath, 'utf8');
const lumaAgentsImageClientSource = readFileSync(lumaAgentsImageClientPath, 'utf8');
const lumaAgentsImageResponseSource = readFileSync(lumaAgentsImageResponsePath, 'utf8');
const lumaAgentsImageErrorSource = readFileSync(lumaAgentsImageErrorPath, 'utf8');
const completionSource = readFileSync(completionPath, 'utf8');
const failureSource = readFileSync(failurePath, 'utf8');
const receiptsSource = readFileSync(receiptsPath, 'utf8');
const settingsSnapshotSource = readFileSync(settingsSnapshotPath, 'utf8');
const imageGenerationTypesSource = readFileSync(imageGenerationTypesPath, 'utf8');
const imageWorkspaceSource = readFileSync(imageWorkspacePath, 'utf8');
const imageGenerationRunnerSource = readFileSync(imageGenerationRunnerPath, 'utf8');

test('image generation executor delegates focused server helpers', () => {
  assert.ok(existsSync(existingJobResponsePath), 'existing image job response helpers should live in a focused module');
  assert.ok(existsSync(referenceNormalizationPath), 'image reference normalization should live in a focused module');
  assert.ok(existsSync(requestContextPath), 'image request context validation should live in a focused module');
  assert.ok(existsSync(referencesPath), 'image reference preparation should live in a focused module');
  assert.ok(
    existsSync(storyboardTemplateReferencePath),
    'storyboard template reference publishing should live in a focused module'
  );
  assert.ok(existsSync(initialJobPath), 'atomic initial image job creation should live in a focused module');
  assert.ok(existsSync(errorPath), 'image generation execution error should live in a focused module');
  assert.ok(existsSync(providerPayloadPath), 'provider payload parsing should live in a focused module');
  assert.ok(existsSync(directProviderExecutionPath), 'direct image provider routing should live in a focused module');
  assert.ok(existsSync(bytePlusSeedreamExecutionPath), 'BytePlus Seedream execution should live in a focused module');
  assert.ok(existsSync(bytePlusSeedreamPayloadPath), 'BytePlus Seedream payload building should live in a focused module');
  assert.ok(existsSync(bytePlusSeedreamClientPath), 'BytePlus Seedream HTTP calls should live in a focused module');
  assert.ok(existsSync(bytePlusSeedreamResponsePath), 'BytePlus Seedream response parsing should live in a focused module');
  assert.ok(existsSync(lumaAgentsImageExecutionPath), 'Luma Agents image direct execution should live in a focused module');
  assert.ok(existsSync(lumaAgentsImagePayloadPath), 'Luma Agents image payload building should live in a focused module');
  assert.ok(existsSync(lumaAgentsImageClientPath), 'Luma Agents image HTTP calls should live in a focused module');
  assert.ok(existsSync(lumaAgentsImageResponsePath), 'Luma Agents image response parsing should live in a focused module');
  assert.ok(existsSync(lumaAgentsImageErrorPath), 'Luma Agents image error classification should live in a focused module');
  assert.ok(existsSync(completionPath), 'image generation completion persistence should live in a focused module');
  assert.ok(existsSync(failurePath), 'image generation failure persistence should live in a focused module');
  assert.ok(existsSync(receiptsPath), 'image generation receipt helpers should live in a focused module');
  assert.ok(existsSync(settingsSnapshotPath), 'image settings snapshot helpers should live in a focused module');
  assert.ok(existsSync(outputStoragePath), 'generated image output storage should live in a focused module');
  assert.match(executorSource, /from '\.\/existing-image-job-response'/);
  assert.match(executorSource, /from '\.\/image-generation-request-context'/);
  assert.match(executorSource, /from '\.\/image-generation-references'/);
  assert.match(executorSource, /from '\.\/image-initial-job'/);
  assert.match(executorSource, /from '\.\/image-generation-error'/);
  assert.match(executorSource, /from '\.\/image-provider-payload'/);
  assert.match(executorSource, /from '\.\/image-direct-provider-execution'/);
  assert.match(executorSource, /from '\.\/luma-agents-execution'/);
  assert.match(executorSource, /from '\.\/image-generation-completion'/);
  assert.match(executorSource, /from '\.\/image-generation-failure'/);
  assert.match(executorSource, /from '\.\/image-generation-receipts'/);
  assert.match(executorSource, /from '\.\/image-generation-settings-snapshot'/);
  assert.match(executorSource, /export \{ buildResponseFromExistingJob \} from '\.\/existing-image-job-response'/);
  assert.match(executorSource, /export \{ ImageGenerationExecutionError \} from '\.\/image-generation-error'/);
});

test('image generation executor does not regain extracted server ownership', () => {
  assert.doesNotMatch(executorSource, /function buildImagesFromExistingJob\(/, 'stored render parsing belongs in existing-image-job-response.ts');
  assert.doesNotMatch(executorSource, /function parseResolutionFromSettingsSnapshot\(/, 'settings snapshot resolution parsing belongs in existing-image-job-response.ts');
  assert.doesNotMatch(executorSource, /parseStoredImageRenders/, 'stored render parsing belongs in existing-image-job-response.ts');
  assert.doesNotMatch(executorSource, /function getImageEngine\(/, 'engine resolution belongs in image-generation-request-context.ts');
  assert.doesNotMatch(executorSource, /function normalizeMode\(/, 'mode normalization belongs in image-generation-request-context.ts');
  assert.doesNotMatch(executorSource, /clampRequestedImageCount/, 'image count clamping belongs in image-generation-request-context.ts');
  assert.doesNotMatch(executorSource, /resolveRequestedAspectRatio/, 'aspect ratio validation belongs in image-generation-request-context.ts');
  assert.doesNotMatch(executorSource, /sanitizeCharacterReferences/, 'character reference sanitizing belongs in image-generation-references.ts');
  assert.doesNotMatch(executorSource, /getReferenceConstraints/, 'reference count validation belongs in image-generation-references.ts');
  assert.doesNotMatch(executorSource, /function pickNormalizedReferenceMime\(/, 'reference mime selection belongs in image-reference-normalization.ts');
  assert.doesNotMatch(executorSource, /function isReferenceImageSupported\(/, 'reference format checks belong in image-reference-normalization.ts');
  assert.doesNotMatch(executorSource, /async function normalizeReferenceImageForEngine\(/, 'reference normalization belongs in image-reference-normalization.ts');
  assert.doesNotMatch(executorSource, /withDbTransaction/, 'initial job transaction belongs in image-initial-job.ts');
  assert.doesNotMatch(executorSource, /reserveWalletChargeInExecutor/, 'wallet reservation belongs in image-initial-job.ts');
  assert.doesNotMatch(executorSource, /async function insertProvisionalImageJob\(/, 'provisional job insert belongs in image-initial-job.ts');
  assert.doesNotMatch(executorSource, /export class ImageGenerationExecutionError/, 'execution error contract belongs in image-generation-error.ts');
  assert.doesNotMatch(executorSource, /function normalizeUrl\(/, 'provider URL normalization belongs in image-provider-payload.ts');
  assert.doesNotMatch(executorSource, /function sanitizeCharacterReferences\(/, 'character reference sanitizing belongs in image-provider-payload.ts');
  assert.doesNotMatch(executorSource, /function buildCharacterReferencePrompt\(/, 'character reference prompt building belongs in image-provider-payload.ts');
  assert.doesNotMatch(executorSource, /function extractImages\(/, 'provider image extraction belongs in image-provider-payload.ts');
  assert.doesNotMatch(executorSource, /images\/generations/, 'BytePlus HTTP routing belongs in byteplus-seedream-client.ts');
  assert.doesNotMatch(executorSource, /extractBytePlusSeedreamImages/, 'BytePlus image extraction belongs in byteplus-seedream-response.ts');
  assert.doesNotMatch(executorSource, /POST \/v1\/generations/, 'Luma direct HTTP routing belongs in luma-agents-client.ts');
  assert.doesNotMatch(executorSource, /buildLumaAgentsImagePayload/, 'Luma image payload building belongs in luma-agents-payload.ts');
  assert.doesNotMatch(executorSource, /copyGeneratedImagesToStorage\(\{[\s\S]+Luma/, 'Luma direct output copy belongs in luma-agents-execution.ts');
  assert.doesNotMatch(executorSource, /function parseRequestId\(/, 'provider request id parsing belongs in image-provider-payload.ts');
  assert.doesNotMatch(executorSource, /function buildReceiptSnapshot\(/, 'receipt snapshots belong in image-generation-receipts.ts');
  assert.doesNotMatch(executorSource, /async function recordRefundReceipt\(/, 'refund receipt writes belong in image-generation-receipts.ts');
  assert.doesNotMatch(executorSource, /function buildDefaultSettingsSnapshot\(/, 'default settings snapshots belong in image-generation-settings-snapshot.ts');
  assert.doesNotMatch(executorSource, /recordUserAsset/, 'completed character asset persistence belongs in image-generation-completion.ts');
  assert.doesNotMatch(executorSource, /upsertLegacyJobOutputs/, 'completed output persistence belongs in image-generation-completion.ts');
  assert.doesNotMatch(executorSource, /ensureReusableAsset/, 'reusable character asset persistence belongs in image-generation-completion.ts');
  assert.doesNotMatch(executorSource, /status = 'completed'/, 'completed job update belongs in image-generation-completion.ts');
  assert.doesNotMatch(executorSource, /ApiError/, 'provider failure classification belongs in image-generation-failure.ts');
  assert.doesNotMatch(executorSource, /ValidationError/, 'provider validation error parsing belongs in image-generation-failure.ts');
  assert.doesNotMatch(executorSource, /status = 'failed'/, 'failed job update belongs in image-generation-failure.ts');
  assert.doesNotMatch(executorSource, /referenceImageHosts/, 'failed provider log metadata belongs in image-generation-failure.ts');

  const lineCount = executorSource.split('\n').length;
  assert.ok(lineCount <= 640, `image generation executor should stay below 640 lines after context extraction, got ${lineCount}`);
});

test('storyboard image billing uses storyboard identity instead of provider display name', () => {
  assert.match(storyboardPricingSource, /STORYBOARD_BILLING_ENGINE_ID = 'storyboarder'/);
  assert.match(storyboardPricingSource, /STORYBOARD_BILLING_LABEL = 'Storyboarder'/);
  assert.match(storyboardPricingSource, /STORYBOARD_INCLUDED_PAYMENT_STATUS = 'included'/);
  assert.match(storyboardPricingSource, /applyStoryboardKlingBundlePricing/);
  assert.match(storyboardPricingSource, /createIncludedStoryboardKlingFirstFramePricing/);
  assert.doesNotMatch(storyboardPricingSource, /storyboard_gpt_image_2/);
  assert.match(storyboardPricingSource, /engineLabel: STORYBOARD_BILLING_LABEL/);
  assert.match(imageGenerateRouteSource, /isStoryboardBillingSource\(body\?\.source\) \? 'storyboard' : 'image'/);
  assert.match(executorSource, /getStoryboardBillingIdentity/);
  assert.match(executorSource, /const billingEngineId = storyboardBillingIdentity\?\.engineId \?\? engine\.id/);
  assert.match(executorSource, /const billingEngineLabel = storyboardBillingIdentity\?\.engineLabel \?\? engine\.label/);
  assert.match(executorSource, /createAtomicInitialImageJob\(\{[\s\S]+engineId: billingEngineId,[\s\S]+engineLabel: billingEngineLabel/);
  assert.match(executorSource, /description = billingProductLabel[\s\S]+billingEngineLabel/);
  assert.match(executorSource, /body\.referenceImageSizes/);
  assert.match(executorSource, /storedReferenceSizes\.length \? storedReferenceSizes : clientReferenceImageSizes/);
  assert.match(executorSource, /applyStoryboardImagePricing/);
  assert.match(executorSource, /resolveIncludedKlingFirstFrameParentJobId/);
  assert.match(executorSource, /walletChargeMode === 'included'/);
  assert.match(storyboardImageBillingSource, /applyStoryboardKlingBundlePricing/);
  assert.match(storyboardImageBillingSource, /createIncludedStoryboardKlingFirstFramePricing/);
  assert.match(storyboardImageBillingSource, /settings_snapshot->'storyboard'->>'targetModel' = 'kling'/);
});

test('existing image job response module exposes the expected contract', () => {
  assert.match(existingJobResponseSource, /export type ExistingImageJobRow/);
  assert.match(existingJobResponseSource, /export function parseResolutionFromSettingsSnapshot/);
  assert.match(existingJobResponseSource, /export function buildResponseFromExistingJob/);
  assert.match(existingJobResponseSource, /parseStoredImageRenders/);
  assert.match(referenceNormalizationSource, /export type StoredAssetInfo/);
  assert.match(referenceNormalizationSource, /export async function getStoredAssetInfoByUrl/);
  assert.match(referenceNormalizationSource, /export function isReferenceImageSupported/);
  assert.match(referenceNormalizationSource, /export function pickNormalizedReferenceMime/);
  assert.match(referenceNormalizationSource, /export async function normalizeReferenceImageForEngine/);
  assert.match(requestContextSource, /export type ImageEngineEntry/);
  assert.match(requestContextSource, /export function resolveImageGenerationRequestContext/);
  assert.match(requestContextSource, /function getImageEngine/);
  assert.match(requestContextSource, /function normalizeMode/);
  assert.match(referencesSource, /export async function prepareImageGenerationReferences/);
  assert.match(referencesSource, /getStoredAssetInfoByUrl/);
  assert.match(referencesSource, /normalizeReferenceImageForEngine/);
  assert.match(referencesSource, /resolveStoryboardTemplateReferenceUrls/);
  assert.match(referencesSource, /getReferenceConstraints/);
  assert.match(storyboardTemplateReferenceSource, /export async function resolveStoryboardTemplateReferenceUrls/);
  assert.match(storyboardTemplateReferenceSource, /storyboard-template-references/);
  assert.match(storyboardTemplateReferenceSource, /storyboard_template_reference/);
  assert.match(storyboardTemplateReferenceSource, /STORYBOARD_TEMPLATE_PATH_PATTERN/);
  assert.match(initialJobSource, /export const PLACEHOLDER_THUMB/);
  assert.match(initialJobSource, /export async function createAtomicInitialImageJob/);
  assert.match(initialJobSource, /ImageWalletChargeMode = 'charge' \| 'included'/);
  assert.match(initialJobSource, /walletChargeMode === 'charge'/);
  assert.match(initialJobSource, /walletChargeMode === 'included'/);
  assert.match(initialJobSource, /async function insertProvisionalImageJob/);
  assert.match(initialJobSource, /withDbTransaction/);
  assert.match(initialJobSource, /reserveWalletChargeInExecutor/);
  assert.match(errorSource, /export class ImageGenerationExecutionError/);
  assert.match(providerPayloadSource, /export function normalizeProviderImageUrl/);
  assert.match(providerPayloadSource, /export function sanitizeCharacterReferences/);
  assert.match(providerPayloadSource, /export function buildCharacterReferencePrompt/);
  assert.match(providerPayloadSource, /export function extractImages/);
  assert.match(providerPayloadSource, /export function parseRequestId/);
  assert.match(directProviderExecutionSource, /executeGoogleVertexImageGeneration/);
  assert.match(directProviderExecutionSource, /executeBytePlusSeedreamGeneration/);
  assert.match(bytePlusSeedreamExecutionSource, /callBytePlusSeedream/);
  assert.match(bytePlusSeedreamExecutionSource, /buildBytePlusSeedreamPayload/);
  assert.match(bytePlusSeedreamExecutionSource, /extractBytePlusSeedreamImages/);
  assert.match(bytePlusSeedreamExecutionSource, /copyGeneratedImagesToStorage/);
  assert.match(lumaAgentsImageExecutionSource, /executeLumaAgentsImageGenerationWithFalFallback/);
  assert.match(lumaAgentsImageExecutionSource, /runFalImageGeneration/);
  assert.match(lumaAgentsImageExecutionSource, /copyGeneratedImagesToStorage/);
  assert.match(lumaAgentsImagePayloadSource, /buildLumaAgentsImagePayload/);
  assert.match(lumaAgentsImageClientSource, /createGeneration/);
  assert.match(lumaAgentsImageResponseSource, /normalizeLumaAgentsImageGeneration/);
  assert.match(lumaAgentsImageErrorSource, /shouldFallbackFromLumaAgentsImageSubmit/);
  assert.match(executorSource, /copyGeneratedImagesToStorage/);
  assert.match(executorSource, /jobSurface === 'storyboard'/);
  assert.match(completionSource, /export async function persistCompletedImageGeneration/);
  assert.match(completionSource, /paymentStatus\?: string/);
  assert.match(completionSource, /payment_status = \$15/);
  assert.doesNotMatch(
    completionSource,
    /recordUserAsset/,
    'character outputs should be persisted once through ensureReusableAsset and its legacy mirror'
  );
  assert.match(completionSource, /upsertLegacyJobOutputs/);
  assert.match(completionSource, /ensureReusableAsset/);
  assert.match(completionSource, /status = 'completed'/);
  assert.match(failureSource, /export async function persistFailedImageGeneration/);
  assert.match(failureSource, /refundOnFailure\?: boolean/);
  assert.match(failureSource, /failedPaymentStatus\?: string/);
  assert.match(failureSource, /if \(refundOnFailure\)/);
  assert.match(failureSource, /ApiError/);
  assert.match(failureSource, /ValidationError/);
  assert.match(failureSource, /recordRefundReceipt/);
  assert.match(failureSource, /status = 'failed'/);
  assert.match(receiptsSource, /export type PendingReceipt/);
  assert.match(receiptsSource, /export function buildReceiptSnapshot/);
  assert.match(receiptsSource, /export async function recordRefundReceipt/);
  assert.match(settingsSnapshotSource, /export function buildDefaultSettingsSnapshot/);
});

test('Luma image style stays wired from workspace request to direct payload', () => {
  assert.match(imageGenerationTypesSource, /style\?: string/);
  assert.match(imageWorkspaceSource, /const \[style, setStyle\] = useState<string \| null>\(null\)/);
  assert.match(imageWorkspaceSource, /styleField/);
  assert.match(imageWorkspaceSource, /hasStyleField: Boolean\(styleField\)/);
  assert.match(imageGenerationRunnerSource, /hasStyleField: boolean/);
  assert.match(imageGenerationRunnerSource, /style: hasStyleField \? style \?\? undefined : undefined/);
  assert.match(executorSource, /getImageFieldValues\(engine, 'style', mode\)/);
  assert.match(executorSource, /body\.style/);
  assert.match(executorSource, /\.\.\.\(style \? \{ style \} : \{\}\)/);
  assert.match(executorSource, /style, engine, engineEntry/);
  assert.match(settingsSnapshotSource, /style: args\.style/);
});
