export const DEFAULT_DASHBOARD_COPY = {
  create: {
    title: 'Create',
    subtitle: 'Start a new render or pick up where you left off.',
    videoTitle: 'Create video',
    videoSubtitle: 'Choose your engine and mode, then start a render.',
    imageTitle: 'Create image',
    imageSubtitle: 'Generate stills or edits with the image engines.',
    engineLabel: 'Engine',
    newVideo: 'New video',
    generateAudio: 'Generate audio',
    useLastVideo: 'Use last video settings',
    startVideoTemplate: 'Start from template',
    newImage: 'New image',
    useLastImage: 'Use last image settings',
    startImageTemplate: 'Start from template',
  },
  modes: {
    t2v: 'T2V',
    i2v: 'I2V',
    ref2v: 'REF',
    fl2v: 'F/L',
    a2v: 'A2V',
    extend: 'Extend',
    retake: 'Retake',
    r2v: 'Reference',
    t2i: 'Create',
    i2i: 'Edit',
  },
  inProgress: {
    title: 'In progress',
    empty: 'No active renders right now.',
    etaLabel: 'ETA',
    progressLabel: 'Progress',
    open: 'Open',
    remix: 'Remix',
  },
  recent: {
    title: 'Recent renders',
    viewAll: 'Open History',
    empty: 'No renders yet. Start a generation to populate your history.',
    tabs: {
      all: 'All',
      video: 'Video',
      image: 'Image',
      storyboard: 'Storyboard',
      character: 'Character',
      angle: 'Angle',
      upscale: 'Upscale',
      'background-removal': 'Background removal',
      audio: 'Audio',
    },
  },
  insights: {
    title: 'Insights',
    spendToday: 'Spend today',
    spend30: 'Spend 30d',
    avgCost: 'Avg cost',
    runway: 'Runway',
    today: 'Today',
    runwayFallback: 'Runway estimate needs completed renders.',
    mostUsed: 'Most used',
  },
  quickStarts: {
    title: 'Quick starts',
    empty: 'Save a render as a template to reuse it here.',
    use: 'Use',
    manage: 'Open Library',
    remove: 'Remove',
    defaultTitle: 'Template',
    meta: {
      engine: 'Engine',
      format: 'Format',
      duration: 'Duration',
      audio: 'Audio',
      audioOn: 'On',
      audioOff: 'Off',
      audioUnknown: '—',
      price: 'Price',
      formatAuto: 'Auto',
    },
  },
  tools: {
    title: 'Tools',
    subtitle: 'Prepare stronger source assets before you generate.',
    allTools: 'Open all tools',
    characterTitle: 'Create a character',
    characterBody: 'Build a reusable character reference for image and video workflows.',
    characterBadge: 'Character reference',
    angleTitle: 'Change angle view',
    angleBody: 'Generate a better camera angle from an existing image.',
    angleBadge: 'New viewpoint',
  },
  engines: {
    title: 'Engine status',
    allOk: 'All engines operational',
    viewStatus: 'View status',
    error: 'Failed to load engines.',
    queueLabel: 'queue: {count}',
  },
  actions: {
    retry: 'Retry',
    loadMore: 'Load more',
    download: 'Download',
    remix: 'Remix',
    template: 'Use as template',
    noPreview: 'No preview',
  },
  lightbox: {
    groupTitle: 'Group ×{count}',
    jobTitle: 'Render {id}',
    metadata: {
      created: 'Created',
      heroDuration: 'Hero duration',
      engine: 'Engine',
      duration: 'Duration',
      status: 'Status',
      notProvided: 'Not provided',
    },
    statusFallback: 'N/A',
    versionLabel: 'Version {index}',
  },
} as const;

export type DashboardCopy = typeof DEFAULT_DASHBOARD_COPY;
