import type { Ref } from 'react';
import type { EngineCaps, EngineInputField, EngineModeUiCaps as CapabilityCaps, Mode } from '@/types/engines';

export interface SettingsControlsProps {
  engine: EngineCaps;
  caps?: CapabilityCaps;
  durationSec: number;
  durationOption?: number | string | null;
  onDurationChange: (value: number | string) => void;
  numFrames?: number | null;
  onNumFramesChange?: (value: number) => void;
  resolution: string;
  onResolutionChange: (value: string) => void;
  aspectRatio: string;
  onAspectRatioChange: (value: string) => void;
  fps: number;
  onFpsChange: (value: number) => void;
  mode: Mode;
  iterations?: number;
  onIterationsChange?: (value: number) => void;
  seedLocked?: boolean;
  onSeedLockedChange?: (value: boolean) => void;
  showLoopControl?: boolean;
  loopEnabled?: boolean;
  onLoopChange?: (value: boolean) => void;
  showAudioControl?: boolean;
  audioEnabled?: boolean;
  onAudioChange?: (value: boolean) => void;
  audioControlDisabled?: boolean;
  audioControlNote?: string;
  focusRefs?: {
    duration?: Ref<HTMLElement>;
    resolution?: Ref<HTMLDivElement>;
  };
  showExtendControl?: boolean;
  cfgScale?: number | null;
  onCfgScaleChange?: (value: number) => void;
  durationManaged?: boolean;
  durationManagedLabel?: string;
  showKlingV3Controls?: boolean;
  showKlingV3VoiceControls?: boolean;
  klingShotType?: 'customize' | 'intelligent';
  onKlingShotTypeChange?: (value: 'customize' | 'intelligent') => void;
  voiceIdsValue?: string;
  onVoiceIdsChange?: (value: string) => void;
  voiceControlActive?: boolean;
  showSeedanceControls?: boolean;
  seedValue?: string;
  onSeedChange?: (value: string) => void;
  cameraFixed?: boolean;
  onCameraFixedChange?: (value: boolean) => void;
  safetyChecker?: boolean;
  onSafetyCheckerChange?: (value: boolean) => void;
  showSafetyCheckerControl?: boolean;
  advancedFields?: Array<{ field: EngineInputField; required: boolean }>;
  advancedFieldValues?: Record<string, unknown>;
  onAdvancedFieldChange?: (field: EngineInputField, value: unknown) => void;
  variant?: 'full' | 'advanced';
}
