export const DEFAULT_STORYBOARD_COPY = {
  disabledTitle: 'Tools are disabled',
  disabledBody: 'Enable `FEATURES.workflows.toolsSection` to access this area.',
  backToTools: 'Tools',
  title: 'Storyboarder',
  subtitle: 'Create a storyboard reference board for Seedance or Kling.',
  subjectStepTitle: 'Describe your idea',
  referenceStepTitle: 'References',
  styleStepTitle: 'Video style',
  modelStepTitle: 'Video model',
  lengthStepTitle: 'Storyboard length',
  optionalAutoLabel: 'Optional · auto if empty',
  subjectLabel: 'Subject',
  subjectPlaceholder: 'Product launch, cooking scene, anime beat...',
  actionLabel: 'Action',
  actionPlaceholder: 'Reveal, pour, walk-in, product rotation...',
  dialogueLabel: 'Dialogues',
  dialoguePlaceholder: 'Voiceover: Ready in thirty seconds.\nTalent: This texture stays rich.',
  visualNotesLabel: 'Scene notes',
  visualNotesPlaceholder: 'Location, mood, camera constraints, objects to avoid...',
  referenceImageLabel: 'Reference images',
  referenceImageTitle: 'Character, product or scene references',
  referenceImageBody: 'Upload up to 4 images to keep the same person, product, prop, packaging, style or location across the board.',
  referenceImageUpload: 'Choose image',
  referenceUploading: 'Uploading...',
  removeReferenceImage: 'Remove',
  referenceSlotNameFallback: 'Reference image',
  targetLabel: 'Video target',
  targetSeedance: 'Seedance',
  targetKling: 'Kling',
  targetRecommendedLabel: 'Recommended',
  recognizablePeopleLabel: 'Recognizable people',
  recognizablePeopleMeta: 'For real or identifiable people, use Kling with a separate visual reference.',
  styleLabel: 'Style',
  durationLabel: 'Duration',
  frameCountLabel: 'Frames',
  formatLabel: 'Format',
  landscapeLabel: 'Landscape',
  landscapeMeta: '16:9 video board',
  portraitLabel: 'Portrait',
  portraitMeta: '9:16 mobile board',
  shortPreset: 'Short',
  mediumPreset: 'Medium',
  longPreset: 'Long',
  shortPresetMeta: '6s · 4 shots',
  mediumPresetMeta: '10s · 6 shots',
  longPresetMeta: '15s · 8 shots',
  framesLabel: 'frames',
  tierLabel: 'Price',
  hdTier: 'HD',
  fourKTier: '4K',
  ultraTier: '4K Ultra',
  hdTierMeta: 'Medium quality',
  fourKTierMeta: 'Medium quality',
  ultraTierMeta: 'High quality',
  generate: 'Generate storyboard',
  generating: 'Generating...',
  generationFootnote: 'This only creates the visual storyboard, not the final video.',
  editLabel: 'Edit request',
  editPlaceholder: 'Change framing, product color, lighting...',
  editAction: 'Apply edit',
  shotMapTitle: 'Shot map',
  shotMapEmptyTitle: 'Planned storyboard beats',
  shotMapEmptyBody: 'Adjust the brief, dialogue, style, duration, or frame count to shape the planned storyboard.',
  emptyTitle: 'Storyboard preview',
  emptyBody: 'Fill the short brief and generate a reference board.',
  previewTitle: 'Storyboard preview',
  generatedPreviewLabel: 'Storyboarder render',
  templateReferenceNote: 'The blank template is sent as a hidden structure reference; your own reference images stay separate.',
  recentTitle: 'Previous storyboards',
  recentHint: 'Click to preview',
  recentEmpty: 'No storyboard renders yet.',
  recentItemFallback: 'Storyboard',
  outputTitle: 'Generated storyboard',
  klingFirstFrameTitle: 'Kling first frame',
  klingFirstFrameMeta: 'Sent to the generator as the start image. The storyboard board is sent separately as reference.',
  applyToGenerator: 'Apply to generator',
  download: 'Download',
  editImage: 'Edit image',
  saveToLibrary: 'Save to Storyboard library',
  savedToLibrary: 'Saved to Storyboard library.',
  missingSubject: 'Add a subject first.',
  klingFirstFrameMissing: 'The Kling first frame is missing. Regenerate the storyboard so the first frame can be prepared.',
  uploadFailed: 'Unable to upload the selected reference image. Try again.',
  uploadTooLarge: 'The selected image is too large. Use an image under {maxMB} MB.',
  generationFailed: 'Storyboard generation failed.',
  authTitle: 'Sign in to generate',
  authBody: 'Storyboard generation and library saves use your MaxVideoAI wallet.',
  authPrimary: 'Log in',
  authSecondary: 'Sign in',
  close: 'Close',
  targetNotes: {
    seedance: 'Seedance is recommended for storyboard boards: product, cooking, film props, animation, stylized or non-human subjects. Real people are excluded.',
    kling: 'Kling supports realistic human scenes: the storyboard price includes a clean HD first frame, then Apply sends that first frame plus the board reference.',
    klingFallback: 'Apply sends the clean first frame as the start image and the storyboard board as the reference shot plan.',
  },
  styles: {
    realistic: 'Realistic',
    anime: 'Anime',
    ugc: 'UGC',
    cinema: 'Cinema',
  },
} as const;

export type StoryboardCopy = typeof DEFAULT_STORYBOARD_COPY;

export function resolveStoryboardWorkspaceCopy(localizedCopy: unknown): StoryboardCopy {
  const localizedValues = (localizedCopy ?? {}) as Partial<StoryboardCopy>;

  return {
    ...DEFAULT_STORYBOARD_COPY,
    ...localizedValues,
    targetNotes: {
      ...DEFAULT_STORYBOARD_COPY.targetNotes,
      ...(localizedValues.targetNotes ?? {}),
    },
    styles: {
      ...DEFAULT_STORYBOARD_COPY.styles,
      ...(localizedValues.styles ?? {}),
    },
  };
}
