export const DEFAULT_BACKGROUND_REMOVAL_COPY = {
  disabledTitle: 'Tools are disabled',
  disabledBody: 'Enable `FEATURES.workflows.toolsSection` to access this area.',
  back: 'Back to tools',
  eyebrow: 'Video cleanup',
  title: 'Video Background Remover',
  subtitle: 'Remove backgrounds from short videos, export transparent WebM or solid-color clips, and reuse results from your media library.',
  sourceTitle: 'Source video',
  sourceBody: 'Upload a short clip, paste an HTTPS video URL, or reuse a saved library video.',
  sourceStep: '1',
  dropzoneTitle: 'Drop a video file here',
  dropzoneBody: 'MP4, MOV, or WebM clips up to 60 seconds.',
  upload: 'Upload video',
  urlLabel: 'Video URL',
  urlPlaceholder: 'https://example.com/source.mp4',
  urlHelp: 'Paste a direct HTTPS video URL.',
  library: 'Library',
  libraryHelp: 'Choose a private video from your media library.',
  libraryRefresh: 'Refresh',
  libraryAll: 'All videos',
  libraryUploaded: 'Uploaded',
  libraryGenerated: 'Generated',
  libraryBackgroundRemoval: 'Background removal',
  metadataLoading: 'Reading video metadata...',
  metadataRequired: 'Add a readable video source to estimate price.',
  metadataReady: 'Ready for background removal',
  durationTooLong: 'This tool supports clips up to 60 seconds.',
  settingsTitle: 'Video settings',
  settingsStep: '2',
  backgroundColor: 'Background',
  outputCodec: 'Output',
  outputCodecHint: 'Use WebM VP9 for transparent playback, or choose MP4/MOV with a green or solid background for editing tools.',
  moreFormats: 'More formats',
  formatRecommendation: 'WebM VP9 is the transparent export. Use MP4 or MOV with a solid background when the destination strips alpha.',
  preserveAudio: 'Preserve audio',
  audioOn: 'audio',
  audioMuted: 'muted',
  priceBeforeGeneration: 'Price shown before generation',
  priceLoading: 'Loading price...',
  priceUnavailable: 'Price unavailable',
  priceReady: 'Estimated for this clip',
  run: 'Remove Background',
  running: 'Processing...',
  previewTitle: 'Preview',
  previewStep: '3',
  sourcePreview: 'Source',
  resultPreview: 'Result',
  compareSource: 'Show source',
  compareResult: 'Show result',
  noPreview: 'Add a video to preview the source.',
  emptyPreviewSource: 'Source clip',
  emptyPreviewResult: 'Transparent result',
  checkerboard: 'Transparent output preview',
  save: 'Save',
  saved: 'Saved to library.',
  saveFailed: 'Could not save this result.',
  download: 'Download',
  copyLink: 'Copy link',
  copied: 'Link copied.',
  recentTitle: 'Recent background removals',
  recentEmpty: 'Finished results will appear here.',
  recentFailed: 'Failed',
  authTitle: 'Sign in to use the tool',
  authBody: 'Background removal uses wallet billing and private library storage.',
} as const;

export type BackgroundRemovalWorkspaceCopy = typeof DEFAULT_BACKGROUND_REMOVAL_COPY;
