import type { EngineCaps } from '../../../types/engines';
import type { RawFalEngineEntry } from './types';

const GPT_IMAGE_2_ENGINE: EngineCaps = {
  id: 'gpt-image-2',
  label: 'GPT Image 2',
  provider: 'OpenAI',
  version: '2',
  status: 'live',
  latencyTier: 'standard',
  queueDepth: 0,
  region: 'global',
  modes: ['t2i', 'i2i'],
  maxDurationSec: 4,
  resolutions: ['landscape_4_3', 'square_hd', 'square', 'portrait_4_3', 'portrait_16_9', 'landscape_16_9', 'custom', 'auto'],
  aspectRatios: ['auto', '16:9', '4:3', '1:1', '3:4', '9:16'],
  fps: [1],
  audio: false,
  upscale4k: true,
  extend: false,
  motionControls: false,
  keyframes: false,
  params: {},
  inputLimits: {
    imageMaxMB: 25,
  },
  inputSchema: {
    required: [
      {
        id: 'prompt',
        type: 'text',
        label: 'Prompt',
        description: 'Describe the image to generate, or the edit to apply to the references.',
      },
    ],
    optional: [
      {
        id: 'num_images',
        type: 'number',
        label: 'Number of images',
        min: 1,
        max: 4,
        step: 1,
        default: 1,
        description: 'Generate up to 4 images per request.',
      },
      {
        id: 'image_urls',
        type: 'image',
        label: 'Reference images',
        description: 'Add source images for edit mode.',
        modes: ['i2i'],
        requiredInModes: ['i2i'],
        minCount: 1,
        maxCount: 4,
        source: 'either',
      },
      {
        id: 'resolution',
        engineParam: 'image_size',
        type: 'enum',
        label: 'Image size',
        modes: ['t2i'],
        values: [
          'landscape_4_3',
          'square_hd',
          'square',
          'portrait_4_3',
          'portrait_16_9',
          'landscape_16_9',
          '1024x768',
          '1024x1024',
          '1024x1536',
          '1920x1080',
          '2560x1440',
          '3840x2160',
          'custom',
        ],
        default: 'landscape_4_3',
        description: 'Provider image_size preset or canonical custom size for text-to-image requests.',
      },
      {
        id: 'resolution',
        engineParam: 'image_size',
        type: 'enum',
        label: 'Image size',
        modes: ['i2i'],
        values: [
          'auto',
          'landscape_4_3',
          'square_hd',
          'square',
          'portrait_4_3',
          'portrait_16_9',
          'landscape_16_9',
          '1024x768',
          '1024x1024',
          '1024x1536',
          '1920x1080',
          '2560x1440',
          '3840x2160',
          'custom',
        ],
        default: 'auto',
        description: 'Use auto to infer the output size, or send a provider image_size preset/custom object.',
      },
      {
        id: 'image_width',
        engineParam: 'image_size.width',
        type: 'number',
        label: 'Custom width',
        modes: ['t2i', 'i2i'],
        min: 16,
        max: 3840,
        step: 16,
        default: 1024,
        description: 'Used when Image size is Custom. Requires multiples of 16 and max edge 3840px.',
      },
      {
        id: 'image_height',
        engineParam: 'image_size.height',
        type: 'number',
        label: 'Custom height',
        modes: ['t2i', 'i2i'],
        min: 16,
        max: 3840,
        step: 16,
        default: 768,
        description: 'Used when Image size is Custom. Total pixels must stay between 655,360 and 8,294,400.',
      },
      {
        id: 'quality',
        type: 'enum',
        label: 'Quality',
        values: ['low', 'medium', 'high'],
        default: 'high',
        description: 'Higher quality costs more and improves fidelity.',
      },
      {
        id: 'output_format',
        type: 'enum',
        label: 'Output format',
        values: ['png', 'jpeg', 'webp'],
        default: 'png',
      },
      {
        id: 'mask_url',
        type: 'image',
        label: 'Mask image URL',
        description: 'Optional public mask image URL for edit requests.',
        modes: ['i2i'],
        minCount: 0,
        maxCount: 1,
        source: 'url',
      },
    ],
    constraints: {
      supportedFormats: ['jpg', 'jpeg', 'png', 'webp'],
      maxImageSizeMB: 25,
      imageSize: {
        multipleOf: 16,
        minPixels: 655360,
        maxPixels: 8294400,
        maxEdge: 3840,
        maxAspectRatio: 3,
      },
    },
  },
  pricingDetails: {
    currency: 'USD',
    perSecondCents: {
      default: 15,
      byResolution: {
        '1024x768': 15,
        '1024x1024': 22,
        '1024x1536': 17,
        '1920x1080': 16,
        '2560x1440': 23,
        '3840x2160': 41,
        landscape_4_3: 15,
        portrait_4_3: 15,
        square: 22,
        square_hd: 22,
        portrait_16_9: 17,
        landscape_16_9: 16,
        custom: 15,
        auto: 22,
      },
    },
  },
  pricing: {
    unit: 'image',
    base: 0.15,
    byResolution: {
      '1024x768': 0.15,
      '1024x1024': 0.22,
      '1024x1536': 0.17,
      '1920x1080': 0.16,
      '2560x1440': 0.23,
      '3840x2160': 0.41,
      landscape_4_3: 0.15,
      portrait_4_3: 0.15,
      square: 0.22,
      square_hd: 0.22,
      portrait_16_9: 0.17,
      landscape_16_9: 0.16,
      custom: 0.15,
      auto: 0.22,
    },
    currency: 'USD',
    notes: 'Provider pricing varies by quality and image_size: 1024x768 costs $0.01/$0.04/$0.15, while 3840x2160 costs $0.02/$0.11/$0.41 for Low/Medium/High.',
  },
  updatedAt: '2026-04-23T00:00:00Z',
  ttlSec: 600,
  providerMeta: {
    provider: 'fal.ai',
    modelSlug: 'openai/gpt-image-2',
  },
  availability: 'available',
  brandId: 'openai',
};


export const GPT_IMAGE_2_FAL_ENGINE_REGISTRY: RawFalEngineEntry[] = [
  {
    id: 'gpt-image-2',
    marketingName: 'GPT Image 2',
    cardTitle: 'GPT Image 2',
    provider: 'OpenAI',
    brandId: 'openai',
    versionLabel: '2',
    availability: 'available',
    logoPolicy: 'textOnly',
    billingNote: 'Provider pricing varies by quality and image_size: canonical sizes run from $0.01 low-quality 1024x768 to $0.41 high-quality 3840x2160.',
    engine: GPT_IMAGE_2_ENGINE,
    modes: [
      {
        mode: 't2i',
        falModelId: 'openai/gpt-image-2',
        ui: {
          modes: ['t2i'],
          resolution: [
            'landscape_4_3',
            'square_hd',
            'square',
            'portrait_4_3',
            'portrait_16_9',
            'landscape_16_9',
            '1024x768',
            '1024x1024',
            '1024x1536',
            '1920x1080',
            '2560x1440',
            '3840x2160',
            'custom',
          ],
          notes: 'Quality-first image generation with strong text rendering, photorealism, and product-shot fidelity.',
        },
      },
      {
        mode: 'i2i',
        falModelId: 'openai/gpt-image-2/edit',
        ui: {
          modes: ['i2i'],
          resolution: [
            'auto',
            'landscape_4_3',
            'square_hd',
            'square',
            'portrait_4_3',
            'portrait_16_9',
            'landscape_16_9',
            '1024x768',
            '1024x1024',
            '1024x1536',
            '1920x1080',
            '2560x1440',
            '3840x2160',
            'custom',
          ],
          acceptsImageFormats: ['jpg', 'jpeg', 'png', 'webp'],
          maxUploadMB: 25,
          notes: 'Upload references for fine-grained edits; optional mask URL and quality controls map to the provider edit endpoint.',
        },
      },
    ],
    defaultFalModelId: 'openai/gpt-image-2',
    seo: {
      title: 'GPT Image 2 - OpenAI Image Generation & Editing | MaxVideoAI',
      description:
        'Use GPT Image 2 in MaxVideoAI for text-to-image, image edits, high-fidelity text rendering, product photography, image_size presets/custom size, quality controls, and PNG/JPEG/WEBP output.',
      canonicalPath: '/models/gpt-image-2',
    },
    type: 'image',
    seoText:
      'GPT Image 2 brings OpenAI’s quality-first image model into the same MaxVideoAI image workspace as Nano Banana: one model selector for text-to-image and image-to-image, with image_size presets, custom width/height, quality, output format, and mask URL controls.',
    media: {
      videoUrl: 'https://media.maxvideoai.com/marketing/marketing/9b886851-850d-447e-8555-4df29f25df6c.png',
      imagePath: 'https://media.maxvideoai.com/marketing/marketing/9b886851-850d-447e-8555-4df29f25df6c.png',
      altText: 'GPT Image 2 sample infographic image preview',
    },
    prompts: [
      {
        title: 'Text-heavy product ad',
        prompt:
          'A polished product campaign still for a coffee bag labeled "Summit Roast", readable flavor notes, warm wooden table, controlled daylight, premium catalog photography.',
        mode: 't2i',
        notes: 'Use High quality when text accuracy and packaging detail matter.',
      },
      {
        title: 'Infographic layout',
        prompt:
          'A clean editorial infographic explaining a creator workflow, precise section labels, icon grid, crisp typography, white background, subtle accent colors.',
        mode: 't2i',
      },
      {
        title: 'Reference product edit',
        prompt:
          'Keep the exact product shape and label hierarchy, replace the background with a bright e-commerce tabletop scene, remove distracting reflections, and preserve readable text.',
        mode: 'i2i',
        notes: 'Upload the product reference, then add a mask URL only when the edit should be constrained.',
      },
    ],
    faqs: [
      {
        question: 'Does GPT Image 2 support both generation and editing?',
        answer:
          'Yes. MaxVideoAI exposes one GPT Image 2 entry with text-to-image mapped to openai/gpt-image-2 and image-to-image mapped to openai/gpt-image-2/edit.',
      },
      {
        question: 'Which GPT Image 2 controls are available?',
        answer:
          'The image workspace exposes image_size presets, canonical custom sizes up to 3840x2160, custom width/height, quality levels, num_images, output format, reference images for edits, and an optional mask URL.',
      },
      {
        question: 'How is GPT Image 2 priced?',
        answer:
          'Provider prices follow the quality x size table: 1024x768 is $0.01 / $0.04 / $0.15 and 3840x2160 is $0.02 / $0.11 / $0.41 for Low / Medium / High before MaxVideoAI account pricing rules.',
      },
    ],
    pricingHint: {
      currency: 'USD',
      amountCents: 15,
      resolution: '1024x768',
      label: 'High quality 1024x768',
    },
    promptExample:
      'High-quality product photo of a coffee bag labeled "Summit Roast", readable packaging text, rustic wood table, soft daylight, catalog-ready composition.',
  },
];
