import type { EngineCaps } from '../../../types/engines';
import type { RawFalEngineEntry } from './types';

const LTX_2_3_ENGINE: EngineCaps = {
  id: 'ltx-2-3',
  label: 'LTX 2.3 Pro',
  provider: 'Lightricks',
  version: '2.3 Pro',
  status: 'live',
  latencyTier: 'standard',
  queueDepth: 0,
  region: 'global',
  modes: ['t2v', 'i2v', 'a2v', 'extend', 'retake'],
  maxDurationSec: 20,
  resolutions: ['1080p', '1440p', '4k'],
  aspectRatios: ['16:9', '9:16'],
  fps: [24, 25, 48, 50],
  audio: true,
  upscale4k: false,
  extend: true,
  motionControls: false,
  keyframes: false,
  params: {},
  inputLimits: {
    imageMaxMB: 25,
    videoMaxMB: 30,
    audioMaxMB: 30,
  },
  inputSchema: {
    required: [
      {
        id: 'prompt',
        type: 'text',
        label: 'Prompt',
        modes: ['t2v', 'i2v', 'retake'],
        requiredInModes: ['t2v', 'i2v', 'retake'],
      },
      {
        id: 'image_url',
        type: 'image',
        label: 'Start image',
        description: 'Used as the first frame for image-to-video generation.',
        modes: ['i2v'],
        requiredInModes: ['i2v'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
      },
      {
        id: 'audio_url',
        type: 'audio',
        label: 'Source audio',
        description: 'Video duration follows the audio length. Use an audio file between 2 and 20 seconds.',
        modes: ['a2v'],
        requiredInModes: ['a2v'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
        minDurationSec: 2,
        maxDurationSec: 20,
      },
      {
        id: 'video_url',
        type: 'video',
        label: 'Source video',
        modes: ['extend', 'retake'],
        requiredInModes: ['extend', 'retake'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
      },
    ],
    optional: [
      {
        id: 'prompt',
        type: 'text',
        label: 'Prompt',
        modes: ['a2v', 'extend'],
      },
      {
        id: 'image_url',
        type: 'image',
        label: 'Start image',
        description: 'Optional first frame to anchor the audio-driven clip.',
        modes: ['a2v'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
      },
      {
        id: 'end_image_url',
        type: 'image',
        label: 'End image',
        description: 'Optional end frame for a start-to-end transition.',
        modes: ['i2v'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
      },
      {
        id: 'duration',
        type: 'enum',
        label: 'Duration (seconds)',
        values: ['6', '8', '10'],
        default: '6',
        modes: ['t2v', 'i2v'],
      },
      {
        id: 'aspect_ratio',
        type: 'enum',
        label: 'Aspect ratio',
        values: ['16:9', '9:16'],
        default: '16:9',
        modes: ['t2v', 'i2v'],
      },
      {
        id: 'resolution',
        type: 'enum',
        label: 'Resolution',
        values: ['1080p', '1440p', '4k'],
        default: '1080p',
        modes: ['t2v', 'i2v'],
      },
      {
        id: 'fps',
        type: 'enum',
        label: 'Frames per second',
        values: ['24', '25', '48', '50'],
        default: '25',
        modes: ['t2v', 'i2v'],
      },
      {
        id: 'generate_audio',
        type: 'enum',
        label: 'Generate audio',
        values: ['true', 'false'],
        default: 'true',
        modes: ['t2v', 'i2v'],
      },
      {
        id: 'guidance_scale',
        type: 'number',
        label: 'Guidance scale',
        description: 'Adjust prompt adherence for LTX 2.3.',
        modes: ['i2v', 'a2v'],
        min: 1,
        max: 50,
      },
      {
        id: 'duration',
        type: 'number',
        label: 'Extension duration (seconds)',
        modes: ['extend'],
        min: 1,
        max: 20,
        default: 5,
      },
      {
        id: 'mode',
        type: 'enum',
        label: 'Extend position',
        modes: ['extend'],
        values: ['start', 'end'],
        default: 'end',
      },
      {
        id: 'context',
        type: 'number',
        label: 'Context window (seconds)',
        modes: ['extend'],
        min: 0,
        max: 20,
      },
      {
        id: 'start_time',
        type: 'number',
        label: 'Start time (seconds)',
        modes: ['retake'],
        min: 0,
        max: 20,
        default: 0,
      },
      {
        id: 'duration',
        type: 'number',
        label: 'Retake duration (seconds)',
        modes: ['retake'],
        min: 2,
        max: 20,
        default: 5,
      },
      {
        id: 'retake_mode',
        type: 'enum',
        label: 'Retake mode',
        modes: ['retake'],
        values: ['replace_audio', 'replace_video', 'replace_audio_and_video'],
        default: 'replace_audio_and_video',
      },
    ],
    constraints: {
      supportedFormats: ['jpg', 'jpeg', 'png', 'webp', 'avif', 'heif'],
      maxImageSizeMB: 25,
      maxVideoSizeMB: 30,
      maxAudioSizeMB: 30,
    },
  },
  pricingDetails: {
    currency: 'USD',
    perSecondCents: {
      default: 6,
      byResolution: {
        '1080p': 6,
        '1440p': 12,
        '4k': 24,
      },
    },
  },
  pricing: {
    unit: 'USD/s',
    base: 0.06,
    byResolution: {
      '1080p': 0.06,
      '1440p': 0.12,
      '4k': 0.24,
    },
    currency: 'USD',
    notes: '$0.47 per 6s @1080p, $0.94 @1440p, $1.87 @4K',
  },
  updatedAt: '2026-03-06T00:00:00Z',
  ttlSec: 600,
  providerMeta: {
    provider: 'lightricks',
    modelSlug: 'fal-ai/ltx-2.3/text-to-video',
  },
  availability: 'available',
  brandId: 'lightricks',
};


export const LTX_2_3_FAL_ENGINE_REGISTRY: RawFalEngineEntry[] = [
  {
    id: 'ltx-2-3',
    marketingName: 'LTX 2.3 Pro',
    cardTitle: 'LTX 2.3 Pro – text, image, audio, extend and retake',
    provider: 'Lightricks',
    brandId: 'lightricks',
    versionLabel: 'Pro',
    availability: 'available',
    logoPolicy: 'textOnly',
    engine: LTX_2_3_ENGINE,
    modes: [
      {
        mode: 't2v',
        falModelId: 'fal-ai/ltx-2.3/text-to-video',
        ui: {
          modes: ['t2v'],
          duration: { options: [6, 8, 10], default: 6 },
          resolution: ['1080p', '1440p', '4k'],
          aspectRatio: ['16:9', '9:16'],
          audioToggle: true,
          fps: [24, 25, 48, 50],
          notes: 'Main LTX 2.3 text-to-video workflow with native audio.',
        },
      },
      {
        mode: 'i2v',
        falModelId: 'fal-ai/ltx-2.3/image-to-video',
        ui: {
          modes: ['i2v'],
          duration: { options: [6, 8, 10], default: 6 },
          resolution: ['1080p', '1440p', '4k'],
          aspectRatio: ['auto', '16:9', '9:16'],
          acceptsImageFormats: ['jpg', 'jpeg', 'png', 'webp', 'avif', 'heif'],
          maxUploadMB: 25,
          audioToggle: true,
          fps: [24, 25, 48, 50],
          notes: 'Animate a still with optional native audio and an optional end frame.',
        },
      },
      {
        mode: 'a2v',
        falModelId: 'fal-ai/ltx-2.3/audio-to-video',
        ui: {
          modes: ['a2v'],
          maxUploadMB: 30,
          notes: 'Requires source audio. Optional prompt, first-frame image, and guidance scale.',
        },
      },
      {
        mode: 'extend',
        falModelId: 'fal-ai/ltx-2.3/extend-video',
        ui: {
          modes: ['extend'],
          duration: { min: 1, default: 5 },
          maxUploadMB: 30,
          notes: 'Extend an existing clip by up to 20s. Choose start/end and optional context seconds.',
        },
      },
      {
        mode: 'retake',
        falModelId: 'fal-ai/ltx-2.3/retake-video',
        ui: {
          modes: ['retake'],
          duration: { min: 2, default: 5 },
          maxUploadMB: 30,
          notes: 'Retake a source clip with prompt, start time, duration, and replace mode controls.',
        },
      },
    ],
    defaultFalModelId: 'fal-ai/ltx-2.3/text-to-video',
    seo: {
      title: 'LTX 2.3 Pro AI Video – Text, Image, Audio, Extend & Retake | MaxVideoAI',
      description:
        'Use LTX 2.3 Pro on MaxVideoAI for text-to-video, image-to-video, audio-to-video, extend-video and retake-video workflows with official 1080p/1440p/4K and 24/25/48/50 fps options.',
      canonicalPath: '/models/ltx-2-3-pro',
    },
    type: 'textImage',
    seoText:
      'LTX 2.3 Pro brings Lightricks text, image, audio, extend, and retake workflows into one page while keeping provider controls coherent by mode: 6–10s text/image clips up to 4K, audio-driven video, plus extend and retake tools for source footage.',
    demoUrl: 'https://media.maxvideoai.com/renders/marketing/cd143fa1-9dca-44ad-98ca-506452d5fd34.mp4',
    media: {
      videoUrl: 'https://media.maxvideoai.com/renders/marketing/cd143fa1-9dca-44ad-98ca-506452d5fd34.mp4',
      imagePath:
        'https://media.maxvideoai.com/renders/301cc489-d689-477f-94c4-0b051deda0bc/f397ab6d-d0ef-44eb-977a-3419f494d17e-job_cda079d3-9895-45a0-866c-2dbf57593463.jpg',
      altText: 'LTX 2.3 Pro temporary demo clip using LTX 2 Pro media',
    },
    prompts: [
      {
        title: 'Trailer beat',
        prompt:
          'A cinematic trailer beat in a neon industrial alley, wet asphalt reflections, slow push-in, atmospheric smoke, 16:9',
        mode: 't2v',
      },
      {
        title: 'Animate a portrait still',
        prompt: 'Subtle head turn, realistic cloth motion, gentle handheld drift, soft practical lights',
        mode: 'i2v',
      },
      {
        title: 'Audio-driven performance',
        prompt: 'Performance-driven camera move that matches the rhythm and emotion of the uploaded audio',
        mode: 'a2v',
      },
    ],
    pricingHint: {
      currency: 'USD',
      amountCents: 47,
      durationSeconds: 6,
      resolution: '1080p',
      label: '6s 1080p clip',
    },
    promptExample:
      'A futuristic alley soaked in rain, cinematic reflections, drifting steam, slow dolly move, dramatic practical lighting',
  },
];
