import {
  LUMA_RAY_32_ASPECT_RATIOS,
  LUMA_RAY_32_DURATIONS,
  LUMA_RAY_32_EDIT_STRENGTHS,
  LUMA_RAY_32_POSE_STRENGTHS,
  LUMA_RAY_32_RESOLUTIONS,
  LUMA_UNI_ASPECT_RATIOS,
  LUMA_UNI_OUTPUT_FORMATS,
  LUMA_UNI_STYLES,
} from '../../lib/luma-agents';

export {
  LUMA_RAY_32_ASPECT_RATIOS,
  LUMA_RAY_32_DURATIONS,
  LUMA_RAY_32_EDIT_STRENGTHS,
  LUMA_RAY_32_POSE_STRENGTHS,
  LUMA_RAY_32_RESOLUTIONS,
  LUMA_UNI_ASPECT_RATIOS,
  LUMA_UNI_OUTPUT_FORMATS,
  LUMA_UNI_STYLES,
};

export const LUMA_UNI_REFERENCE_IMAGE_LIMIT_T2I = 9;
export const LUMA_UNI_REFERENCE_IMAGE_LIMIT_EDIT = 8;
export const LUMA_UNI_REFERENCE_IMAGE_LIMIT_EDIT_TOTAL = LUMA_UNI_REFERENCE_IMAGE_LIMIT_EDIT + 1;
export const LUMA_UNI_IMAGE_MAX_MB = 50;

export const LUMA_RAY_32_IMAGE_MAX_MB = 50;
export const LUMA_RAY_32_VIDEO_MAX_MB = 200;
export const LUMA_RAY_32_VIDEO_MAX_DURATION_SEC = 30;
export const LUMA_RAY_32_REFERENCE_IMAGE_UI_LIMIT = 64;

export const LUMA_SUPPORTED_IMAGE_FORMATS = ['jpg', 'jpeg', 'png', 'webp'] as const;
export const LUMA_SUPPORTED_VIDEO_FORMATS = ['mp4', 'mov', 'webm', 'm4v'] as const;
