import type { EngineCaps } from '../../../types/engines';
import { LUMA_AGENTS_PROVIDER, LUMA_RAY_32_FAL_MODEL_BY_MODE } from '../../lib/luma-agents';
import {
  LUMA_RAY_32_ASPECT_RATIOS,
  LUMA_RAY_32_DURATIONS,
  LUMA_RAY_32_EDIT_STRENGTHS,
  LUMA_RAY_32_IMAGE_MAX_MB,
  LUMA_RAY_32_POSE_STRENGTHS,
  LUMA_RAY_32_REFERENCE_IMAGE_UI_LIMIT,
  LUMA_RAY_32_RESOLUTIONS,
  LUMA_RAY_32_VIDEO_MAX_DURATION_SEC,
  LUMA_RAY_32_VIDEO_MAX_MB,
  LUMA_SUPPORTED_IMAGE_FORMATS,
  LUMA_SUPPORTED_VIDEO_FORMATS,
} from './luma-agents-shared';
import type { RawFalEngineEntry } from './types';

const LUMA_RAY_3_2_ENGINE: EngineCaps = {
  id: 'luma-ray-3-2',
  label: 'Luma Ray 3.2',
  provider: 'Luma AI',
  version: 'Ray 3.2',
  status: 'live',
  latencyTier: 'standard',
  queueDepth: 0,
  region: 'global',
  modes: ['t2v', 'i2v', 'v2v', 'reframe'],
  maxDurationSec: 30,
  resolutions: [...LUMA_RAY_32_RESOLUTIONS],
  aspectRatios: [...LUMA_RAY_32_ASPECT_RATIOS] as EngineCaps['aspectRatios'],
  fps: [24],
  audio: false,
  upscale4k: false,
  extend: false,
  motionControls: true,
  keyframes: true,
  params: {},
  inputLimits: {
    imageMaxMB: LUMA_RAY_32_IMAGE_MAX_MB,
    videoMaxMB: LUMA_RAY_32_VIDEO_MAX_MB,
    videoMaxDurationSec: LUMA_RAY_32_VIDEO_MAX_DURATION_SEC,
  },
  inputSchema: {
    required: [
      {
        id: 'prompt',
        type: 'text',
        label: 'Prompt',
        modes: ['t2v', 'i2v', 'v2v', 'reframe'],
        requiredInModes: ['t2v', 'i2v', 'v2v', 'reframe'],
        description: 'Describe the video motion, subject, camera, edit, style, or new canvas area.',
      },
      {
        id: 'image_url',
        type: 'image',
        label: 'Start image',
        description: 'Use one source image to anchor the opening frame for image-to-video.',
        modes: ['i2v'],
        requiredInModes: ['i2v'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
      },
      {
        id: 'video_url',
        type: 'video',
        label: 'Source video',
        description: 'Use one MP4/MOV/WebM source clip for Ray 3.2 Modify or Reframe.',
        modes: ['v2v', 'reframe'],
        requiredInModes: ['v2v', 'reframe'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
        maxDurationSec: LUMA_RAY_32_VIDEO_MAX_DURATION_SEC,
      },
    ],
    optional: [
      {
        id: 'duration',
        type: 'enum',
        label: 'Duration',
        values: [...LUMA_RAY_32_DURATIONS],
        default: '5s',
        modes: ['t2v', 'i2v', 'v2v'],
      },
      {
        id: 'aspect_ratio',
        type: 'enum',
        label: 'Aspect ratio',
        values: [...LUMA_RAY_32_ASPECT_RATIOS],
        default: '16:9',
        modes: ['t2v', 'i2v', 'reframe'],
      },
      {
        id: 'resolution',
        type: 'enum',
        label: 'Resolution',
        values: [...LUMA_RAY_32_RESOLUTIONS],
        default: '720p',
        modes: ['t2v', 'i2v', 'v2v', 'reframe'],
      },
      {
        id: 'loop',
        type: 'boolean',
        label: 'Loop video',
        default: false,
        modes: ['t2v', 'i2v'],
        description: 'Loop is supported for 5s requests. 10s loop requests are provider-limited.',
      },
      {
        id: 'hdr',
        type: 'boolean',
        label: 'HDR',
        default: false,
        modes: ['t2v', 'i2v', 'v2v'],
        description: 'Generate an HDR MP4 when Luma direct supports the selected duration and resolution.',
      },
      {
        id: 'exr_export',
        type: 'boolean',
        label: 'EXR export',
        default: false,
        modes: ['t2v', 'i2v', 'v2v'],
        description: 'Export an EXR file alongside the MP4. Requires HDR and routes direct to Luma.',
      },
      {
        id: 'end_image_url',
        type: 'image',
        label: 'End image',
        description: 'Optional final frame for 5s image-to-video interpolation. Not compatible with loop.',
        modes: ['i2v'],
        minCount: 0,
        maxCount: 1,
        source: 'either',
      },
      {
        id: 'start_image_url',
        type: 'image',
        label: 'Guide frame',
        description: 'Optional single guide frame for Ray 3.2 Modify. Do not combine with multi-keyframes.',
        modes: ['v2v'],
        minCount: 0,
        maxCount: 1,
        source: 'either',
      },
      {
        id: 'edit_keyframe_urls',
        type: 'image',
        label: 'Modify keyframes',
        description: 'Optional guide frames pinned to source-video frame indexes. Provide indexes below in the same order.',
        modes: ['v2v'],
        minCount: 0,
        maxCount: LUMA_RAY_32_REFERENCE_IMAGE_UI_LIMIT,
        source: 'either',
        slotLabelPattern: 'Frame {n}',
      },
      {
        id: 'edit_keyframe_indexes',
        type: 'text',
        label: 'Keyframe indexes',
        description: 'Comma-separated source frame indexes for Modify keyframes, for example 0, 48, 96.',
        modes: ['v2v'],
      },
      {
        id: 'edit_strength',
        type: 'enum',
        label: 'Modify strength',
        description: 'Auto lets Luma derive controls. Adhere preserves motion; Flex balances; Reimagine gives the prompt more freedom.',
        values: [...LUMA_RAY_32_EDIT_STRENGTHS],
        default: 'auto',
        modes: ['v2v'],
      },
      {
        id: 'edit_pose_strength',
        type: 'enum',
        label: 'Pose control',
        description: 'Optional manual pose conditioning. Any manual control disables auto controls.',
        values: [...LUMA_RAY_32_POSE_STRENGTHS],
        default: 'off',
        modes: ['v2v'],
      },
      {
        id: 'edit_depth_blur',
        type: 'number',
        label: 'Depth freedom',
        description: 'Optional depth blur from 0 to 1. Higher values allow more geometry freedom.',
        min: 0,
        max: 1,
        step: 0.05,
        modes: ['v2v'],
      },
      {
        id: 'edit_normals_augmentation',
        type: 'number',
        label: 'Normals freedom',
        description: 'Optional surface-normal augmentation from 0 to 1.',
        min: 0,
        max: 1,
        step: 0.05,
        modes: ['v2v'],
      },
      {
        id: 'edit_trajectory_sparsity',
        type: 'number',
        label: 'Trajectory sparsity',
        description: 'Optional motion-trajectory sparsity from 0 to 1.',
        min: 0,
        max: 1,
        step: 0.05,
        modes: ['v2v'],
      },
      {
        id: 'edit_face',
        type: 'boolean',
        label: 'Face control',
        description: 'Enable face-identity conditioning when the source has a face.',
        default: false,
        modes: ['v2v'],
      },
      {
        id: 'source_position_x_norm',
        type: 'number',
        label: 'Source X',
        description: 'Optional source rectangle x position for Reframe, normalized to output width.',
        min: -2,
        max: 2,
        step: 0.05,
        modes: ['reframe'],
      },
      {
        id: 'source_position_y_norm',
        type: 'number',
        label: 'Source Y',
        description: 'Optional source rectangle y position for Reframe, normalized to output height.',
        min: -2,
        max: 2,
        step: 0.05,
        modes: ['reframe'],
      },
      {
        id: 'source_position_w_norm',
        type: 'number',
        label: 'Source width',
        description: 'Optional source rectangle width for Reframe, normalized to output width.',
        min: 0.05,
        max: 2,
        step: 0.05,
        modes: ['reframe'],
      },
      {
        id: 'source_position_h_norm',
        type: 'number',
        label: 'Source height',
        description: 'Optional source rectangle height for Reframe, normalized to output height.',
        min: 0.05,
        max: 2,
        step: 0.05,
        modes: ['reframe'],
      },
    ],
    constraints: {
      supportedFormats: [...LUMA_SUPPORTED_IMAGE_FORMATS, ...LUMA_SUPPORTED_VIDEO_FORMATS],
      maxImageSizeMB: LUMA_RAY_32_IMAGE_MAX_MB,
      maxVideoSizeMB: LUMA_RAY_32_VIDEO_MAX_MB,
      maxVideoDurationSec: LUMA_RAY_32_VIDEO_MAX_DURATION_SEC,
    },
  },
  updatedAt: '2026-06-09T00:00:00Z',
  ttlSec: 600,
  providerMeta: {
    provider: LUMA_AGENTS_PROVIDER,
    modelSlug: 'ray-3-2',
  },
  availability: 'available',
  brandId: 'luma',
};

export const LUMA_RAY_3_2_FAL_ENGINE_REGISTRY: RawFalEngineEntry[] = [
  {
    id: 'luma-ray-3-2',
    marketingName: 'Luma Ray 3.2',
    cardTitle: 'Luma Ray 3.2',
    provider: 'Luma AI',
    brandId: 'luma',
    versionLabel: 'Ray 3.2',
    availability: 'available',
    logoPolicy: 'logoAllowed',
    engine: LUMA_RAY_3_2_ENGINE,
    modes: [
      {
        mode: 't2v',
        falModelId: LUMA_RAY_32_FAL_MODEL_BY_MODE.t2v,
        ui: {
          modes: ['t2v'],
          duration: { options: [...LUMA_RAY_32_DURATIONS], default: '5s' },
          resolution: [...LUMA_RAY_32_RESOLUTIONS],
          aspectRatio: [...LUMA_RAY_32_ASPECT_RATIOS],
          acceptsImageFormats: [...LUMA_SUPPORTED_IMAGE_FORMATS],
          maxUploadMB: LUMA_RAY_32_IMAGE_MAX_MB,
          audioToggle: false,
        },
      },
      {
        mode: 'i2v',
        falModelId: LUMA_RAY_32_FAL_MODEL_BY_MODE.i2v,
        ui: {
          modes: ['i2v'],
          duration: { options: [...LUMA_RAY_32_DURATIONS], default: '5s' },
          resolution: [...LUMA_RAY_32_RESOLUTIONS],
          aspectRatio: [...LUMA_RAY_32_ASPECT_RATIOS],
          acceptsImageFormats: [...LUMA_SUPPORTED_IMAGE_FORMATS],
          maxUploadMB: LUMA_RAY_32_IMAGE_MAX_MB,
          audioToggle: false,
          notes: 'Animate one source image, with optional reference images for style or subject guidance.',
        },
      },
      {
        mode: 'v2v',
        falModelId: 'luma/agent/ray/v3.2/video-edit',
        ui: {
          modes: ['v2v'],
          duration: { options: [...LUMA_RAY_32_DURATIONS], default: '5s' },
          resolution: [...LUMA_RAY_32_RESOLUTIONS],
          acceptsImageFormats: [...LUMA_SUPPORTED_IMAGE_FORMATS],
          maxUploadMB: LUMA_RAY_32_VIDEO_MAX_MB,
          audioToggle: false,
          notes: 'Modify a source video with Ray 3.2 using source-video conditioning, strength presets, guide frames, and keyframes.',
        },
      },
      {
        mode: 'reframe',
        falModelId: 'luma/agent/ray/v3.2/reframe',
        ui: {
          modes: ['reframe'],
          resolution: [...LUMA_RAY_32_RESOLUTIONS],
          aspectRatio: [...LUMA_RAY_32_ASPECT_RATIOS],
          acceptsImageFormats: [...LUMA_SUPPORTED_IMAGE_FORMATS],
          maxUploadMB: LUMA_RAY_32_VIDEO_MAX_MB,
          audioToggle: false,
          notes: 'Outpaint a source video into a new Ray 3.2 aspect ratio while preserving the original content frame-for-frame.',
        },
      },
    ],
    defaultFalModelId: LUMA_RAY_32_FAL_MODEL_BY_MODE.t2v,
    seo: {
      title: 'Luma Ray 3.2 Modify Video and Reframe | MaxVideoAI',
      description:
        'Use Luma Ray 3.2 in MaxVideoAI for source-video Modify, AI video Reframe, guide/keyframe controls, and supporting text-to-video or image-to-video tests.',
      canonicalPath: '/models/luma-ray-3-2',
    },
    type: 'Modify and reframe video',
    seoText:
      'Luma Ray 3.2 is available in MaxVideoAI for source-video Modify, Reframe delivery cuts, guide/keyframe edit passes, and short silent text-to-video or image-to-video tests.',
    demoUrl: '/hero/luma-dream.mp4',
    media: {
      videoUrl: '/hero/luma-dream.mp4',
      imagePath: '/hero/luma-dream.jpg',
      altText: 'Cinematic AI video frame for Luma Ray 3.2',
    },
    prompts: [
      {
        title: 'Modify source product clip',
        prompt:
          'Keep the original camera move and timing from the source video, change the room into a bright editorial showroom, preserve product scale and subject motion.',
        mode: 'v2v',
      },
    ],
    promptExample:
      'Handheld cinematic shot of a designer chair in a sunlit studio, subtle parallax, soft fabric movement, 5s, 16:9.',
  },
];
