import type { EngineCaps } from '../../../types/engines';
import type { RawFalEngineEntry } from './types';

const VEO_3_1_FAST_ENGINE: EngineCaps = {
  id: 'veo-3-1-fast',
  label: 'Google Veo 3.1 Fast',
  provider: 'Google',
  version: '3.1 Fast',
  status: 'live',
  latencyTier: 'fast',
  queueDepth: 0,
  region: 'global',
  modes: ['t2v', 'i2v', 'ref2v', 'fl2v', 'extend'],
  maxDurationSec: 8,
  resolutions: ['720p', '1080p', '4k'],
  aspectRatios: ['16:9', '9:16'],
  fps: [24],
  audio: true,
  upscale4k: false,
  extend: true,
  motionControls: false,
  keyframes: false,
  params: {},
  inputLimits: {
    imageMaxMB: 20,
  },
  inputSchema: {
    required: [
      {
        id: 'prompt',
        type: 'text',
        label: 'Prompt',
      },
      {
        id: 'image_url',
        type: 'image',
        label: 'Start image',
        description: 'Use one still image as the starting frame for the shot.',
        modes: ['i2v'],
        requiredInModes: ['i2v'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
      },
      {
        id: 'image_urls',
        type: 'image',
        label: 'Reference images',
        description: 'Attach 1-3 stills to preserve identity, styling, wardrobe, or product details.',
        modes: ['ref2v'],
        requiredInModes: ['ref2v'],
        minCount: 1,
        maxCount: 3,
        source: 'either',
      },
      {
        id: 'first_frame_url',
        type: 'image',
        label: 'Start image',
        description: 'Opening frame for the shot.',
        modes: ['fl2v'],
        requiredInModes: ['fl2v'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
      },
      {
        id: 'last_frame_url',
        type: 'image',
        label: 'Last frame',
        description: 'Target ending image for the shot.',
        modes: ['fl2v'],
        requiredInModes: ['fl2v'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
      },
      {
        id: 'video_url',
        type: 'video',
        label: 'Source video',
        description: 'Extend an existing Veo Fast render from a source clip URL or upload.',
        modes: ['extend'],
        requiredInModes: ['extend'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
      },
    ],
    optional: [
      {
        id: 'duration',
        type: 'enum',
        label: 'Duration',
        values: ['4s', '6s', '8s'],
        default: '8s',
        modes: ['t2v', 'i2v', 'ref2v', 'fl2v'],
        min: 4,
        max: 8,
      },
      {
        id: 'aspect_ratio',
        type: 'enum',
        label: 'Aspect ratio',
        values: ['16:9', '9:16'],
        default: '16:9',
      },
      {
        id: 'resolution',
        type: 'enum',
        label: 'Resolution',
        values: ['720p', '1080p', '4k'],
        default: '720p',
      },
      {
        id: 'seed',
        type: 'number',
        label: 'Seed',
        description: 'Lock motion & noise for iterative runs.',
        modes: ['t2v'],
      },
      {
        id: 'person_generation',
        type: 'enum',
        label: 'People generation',
        values: ['allow_adult', 'dont_allow'],
        default: 'allow_adult',
      },
      {
        id: 'compression_quality',
        type: 'enum',
        label: 'Compression quality',
        values: ['optimized', 'lossless'],
        default: 'optimized',
      },
      {
        id: 'resize_mode',
        type: 'enum',
        label: 'Resize mode',
        values: ['pad', 'crop'],
        default: 'pad',
        modes: ['i2v', 'fl2v'],
      },
      {
        id: 'generate_audio',
        type: 'enum',
        label: 'Generate audio',
        values: ['true', 'false'],
        default: 'true',
      },
      {
        id: 'duration',
        type: 'enum',
        label: 'Extension duration (seconds)',
        modes: ['extend'],
        values: ['7s'],
        default: '7s',
      },
    ],
    constraints: {
      supportedFormats: ['jpg', 'jpeg', 'png'],
    },
  },
  pricingDetails: {
    currency: 'USD',
    perSecondCents: {
      default: 10,
      byResolution: {
        '720p': 10,
        '1080p': 12,
        '4k': 30,
      },
    },
    addons: {
      audio_off: {
        perSecondCentsByResolution: {
          '720p': -2,
          '1080p': -2,
          '4k': -5,
        },
      },
    },
  },
  pricing: {
    unit: 'USD/s',
    base: 0.1,
    byResolution: {
      '720p': 0.1,
      '1080p': 0.12,
      '4k': 0.3,
    },
    currency: 'USD',
    notes: '$0.10/s at 720p with audio, $0.12/s at 1080p with audio, $0.30/s at 4K with audio; audio off follows Google video-only rates',
  },
  updatedAt: '2025-02-14T00:00:00Z',
  ttlSec: 600,
  providerMeta: {
    provider: 'google-veo',
    modelSlug: 'fal-ai/veo3.1/fast',
  },
  availability: 'available',
  brandId: 'google-veo',
};


export const VEO_3_1_FAST_FAL_ENGINE_REGISTRY: RawFalEngineEntry[] = [
  {
    id: 'veo-3-1-fast',
    marketingName: 'Google Veo 3.1 Fast',
    cardTitle: 'Veo 3.1 Fast',
    provider: 'Google',
    brandId: 'google-veo',
    versionLabel: '3.1 Fast',
    availability: 'available',
    logoPolicy: 'textOnly',
    engine: VEO_3_1_FAST_ENGINE,
    modes: [
      {
        mode: 't2v',
        falModelId: 'fal-ai/veo3.1/fast',
        ui: {
          modes: ['t2v'],
          duration: { options: ['4s', '6s', '8s'], default: '8s' },
          resolution: ['720p', '1080p', '4k'],
          aspectRatio: ['16:9', '9:16'],
          audioToggle: true,
        },
      },
      {
        mode: 'i2v',
        falModelId: 'fal-ai/veo3.1/fast/image-to-video',
        ui: {
          modes: ['i2v'],
          duration: { options: ['4s', '6s', '8s'], default: '8s' },
          resolution: ['720p', '1080p', '4k'],
          aspectRatio: ['16:9', '9:16'],
          audioToggle: true,
          acceptsImageFormats: ['jpg', 'jpeg', 'png'],
          maxUploadMB: 20,
          notes: 'Animate one still quickly while keeping Veo Fast native audio optional.',
        },
      },
      {
        mode: 'ref2v',
        falModelId: 'fal-ai/veo3.1/fast/reference-to-video',
        ui: {
          modes: ['ref2v'],
          duration: { options: ['8s'], default: '8s' },
          resolution: ['720p', '1080p', '4k'],
          aspectRatio: ['16:9', '9:16'],
          audioToggle: true,
          acceptsImageFormats: ['jpg', 'jpeg', 'png'],
          maxUploadMB: 20,
          notes: 'Attach multiple stills to keep identity, styling, and products consistent in a faster Veo pass.',
        },
      },
      {
        mode: 'fl2v',
        falModelId: 'fal-ai/veo3.1/fast/first-last-frame-to-video',
        ui: {
          modes: ['fl2v'],
          duration: { options: ['4s', '6s', '8s'], default: '8s' },
          resolution: ['720p', '1080p', '4k'],
          aspectRatio: ['16:9', '9:16'],
          audioToggle: true,
          acceptsImageFormats: ['jpg', 'jpeg', 'png'],
          maxUploadMB: 20,
          notes: 'Use two keyframes for faster start-to-end bridging while keeping Veo Fast pricing and latency.',
        },
      },
      {
        mode: 'extend',
        falModelId: 'fal-ai/veo3.1/fast/extend-video',
        ui: {
          modes: ['extend'],
          duration: { options: ['7s'], default: '7s' },
          resolution: ['720p', '1080p', '4k'],
          aspectRatio: ['16:9', '9:16'],
          maxUploadMB: 30,
          audioToggle: true,
          notes: 'Extend an existing Veo-generated MP4 by 7 seconds on the Google direct Fast route, including 4K when selected.',
        },
      },
    ],
    defaultFalModelId: 'fal-ai/veo3.1/fast',
    seo: {
      title: 'Veo 3.1 Fast - Text, References, Last Frame & Extend Video',
      description:
        'Use Veo 3.1 Fast for affordable text prompts, start-image animation, multi-reference guidance, optional last-frame control, and extend workflows with optional native audio inside one unified MaxVideoAI model page.',
      canonicalPath: '/models/veo-3-1-fast',
    },
    type: 'Text, start image, references, last frame, extend',
    seoText:
      'Veo 3.1 Fast keeps quick prompt iteration, single start-image animation, multi-reference guidance, optional last-frame control, and extend-video workflows inside one lower-cost DeepMind route with optional audio.',
    demoUrl: '/hero/veo3.mp4',
    media: {
      videoUrl: '/hero/veo3.mp4',
      imagePath: '/hero/veo-3-1-hero.jpg',
      altText: 'Fast rendering sample with Veo 3.1 Fast',
    },
    prompts: [
      {
        title: 'Street interview',
        prompt: 'Casual street interview on a busy sidewalk, handheld camera, native dialogue: “Have you seen Veo 3.1 Fast inside MaxVideoAI?”',
        mode: 't2v',
      },
      {
        title: 'Misty forest zoom',
        prompt: 'Animate a still of a misty forest at dawn, slow zoom toward a mossy rock as sun rays pierce the trees, optional ambient birdsong.',
        mode: 'i2v',
        notes: 'Upload a single start image and enable audio for subtle ambience or leave it off for silent loops.',
      },
      {
        title: 'Reference fidelity shot',
        prompt: 'Eight second tracking shot of the hero walking through neon city streets, keep wardrobe, face, and product details from the reference stills, cinematic lighting.',
        mode: 'ref2v',
        notes: 'Attach 1-3 stills via Reference images to lock identity while staying on the Fast route.',
      },
      {
        title: 'Storyboard bridge',
        prompt: 'Animate between a rough opening storyboard panel and a polished final composition, camera pushes forward, preserve character blocking and reveal timing.',
        mode: 'fl2v',
        notes: 'Use two keyframes when you need speed and tighter transition control.',
      },
    ],
    faqs: [
      {
        question: 'Does Veo 3 ship with the latest motion tuning?',
        answer: 'Yes. MaxVideoAI syncs routing with Google DeepMind updates so motion tuning stays current without manual work.',
      },
      {
        question: 'Can I use more than one image with Veo 3.1 Fast?',
        answer:
          'Yes. Use Reference mode for multiple stills, Generate Video with a single start image, or add a Last frame when you need to steer the ending.',
      },
    ],
    pricingHint: {
      currency: 'USD',
      amountCents: 120,
      durationSeconds: 8,
      resolution: '1080p',
      label: 'Audio on',
    },
    promptExample:
      'A person walking alone on a bridge at night, city lights in the background, camera tracks from behind, ambient street noise',
  },
];
