import type { EngineCaps } from '../../../types/engines';
import type { RawFalEngineEntry } from './types';

const VEO_3_1_ENGINE: EngineCaps = {
  id: 'veo-3-1',
  label: 'Google Veo 3.1',
  provider: 'Google',
  version: '3.1',
  status: 'live',
  latencyTier: 'standard',
  queueDepth: 0,
  region: 'global',
  modes: ['t2v', 'i2v', 'ref2v', 'fl2v', 'extend'],
  maxDurationSec: 8,
  resolutions: ['720p', '1080p', '4k'],
  aspectRatios: ['16:9', '9:16'],
  fps: [24],
  audio: true,
  upscale4k: false,
  extend: true,
  motionControls: false,
  keyframes: false,
  params: {},
  inputLimits: {
    imageMaxMB: 20,
  },
  inputSchema: {
    required: [
      {
        id: 'prompt',
        type: 'text',
        label: 'Prompt',
      },
      {
        id: 'image_url',
        type: 'image',
        label: 'Start image',
        description: 'Use one still image as the starting frame for the shot.',
        modes: ['i2v'],
        requiredInModes: ['i2v'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
      },
      {
        id: 'image_urls',
        type: 'image',
        label: 'Reference images',
        modes: ['ref2v'],
        requiredInModes: ['ref2v'],
        minCount: 1,
        maxCount: 3,
        source: 'either',
      },
      {
        id: 'first_frame_url',
        type: 'image',
        label: 'Start image',
        description: 'Opening frame for the shot.',
        modes: ['fl2v'],
        requiredInModes: ['fl2v'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
      },
      {
        id: 'last_frame_url',
        type: 'image',
        label: 'Last frame',
        description: 'Target ending image for the shot.',
        modes: ['fl2v'],
        requiredInModes: ['fl2v'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
      },
      {
        id: 'video_url',
        type: 'video',
        label: 'Source video',
        description: 'Extend an existing Veo render from a source clip URL or upload.',
        modes: ['extend'],
        requiredInModes: ['extend'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
      },
    ],
    optional: [
      {
        id: 'duration',
        type: 'enum',
        label: 'Duration',
        values: ['4s', '6s', '8s'],
        default: '8s',
        modes: ['t2v', 'i2v', 'ref2v', 'fl2v'],
        min: 4,
        max: 8,
      },
      {
        id: 'aspect_ratio',
        type: 'enum',
        label: 'Aspect ratio',
        values: ['16:9', '9:16'],
        default: '16:9',
      },
      {
        id: 'resolution',
        type: 'enum',
        label: 'Resolution',
        values: ['720p', '1080p', '4k'],
        default: '720p',
      },
      {
        id: 'seed',
        type: 'number',
        label: 'Seed',
        description: 'Lock motion & noise for iterative runs.',
        modes: ['t2v'],
      },
      {
        id: 'person_generation',
        type: 'enum',
        label: 'People generation',
        values: ['allow_adult', 'dont_allow'],
        default: 'allow_adult',
      },
      {
        id: 'compression_quality',
        type: 'enum',
        label: 'Compression quality',
        values: ['optimized', 'lossless'],
        default: 'optimized',
      },
      {
        id: 'resize_mode',
        type: 'enum',
        label: 'Resize mode',
        values: ['pad', 'crop'],
        default: 'pad',
        modes: ['i2v', 'fl2v'],
      },
      {
        id: 'generate_audio',
        type: 'enum',
        label: 'Generate audio',
        values: ['true', 'false'],
        default: 'true',
      },
      {
        id: 'duration',
        type: 'enum',
        label: 'Extension duration (seconds)',
        modes: ['extend'],
        values: ['7s'],
        default: '7s',
      },
    ],
    constraints: {
      supportedFormats: ['jpg', 'jpeg', 'png'],
    },
  },
  pricingDetails: {
    currency: 'USD',
    perSecondCents: {
      default: 40,
      byResolution: {
        '720p': 40,
        '1080p': 40,
        '4k': 60,
      },
    },
    addons: {
      audio_off: {
        perSecondCentsByResolution: {
          '720p': -20,
          '1080p': -20,
          '4k': -20,
        },
      },
    },
  },
  pricing: {
    unit: 'USD/s',
    base: 0.4,
    byResolution: {
      '720p': 0.4,
      '1080p': 0.4,
      '4k': 0.6,
    },
    currency: 'USD',
    notes: '$0.40/s with audio at 720p/1080p, $0.60/s with audio at 4K; audio off is $0.20/s cheaper',
  },
  updatedAt: '2025-02-14T00:00:00Z',
  ttlSec: 600,
  providerMeta: {
    provider: 'google-veo',
    modelSlug: 'fal-ai/veo3.1',
  },
  availability: 'available',
  brandId: 'google-veo',
};


export const VEO_3_1_FAL_ENGINE_REGISTRY: RawFalEngineEntry[] = [
  {
    id: 'veo-3-1',
    marketingName: 'Google Veo 3.1',
    cardTitle: 'Veo 3.1',
    provider: 'Google',
    brandId: 'google-veo',
    versionLabel: '3.1',
    availability: 'available',
    logoPolicy: 'textOnly',
    engine: VEO_3_1_ENGINE,
    modes: [
      {
        mode: 't2v',
        falModelId: 'fal-ai/veo3.1',
        ui: {
          modes: ['t2v'],
          duration: { options: ['4s', '6s', '8s'], default: '8s' },
          resolution: ['720p', '1080p', '4k'],
          aspectRatio: ['16:9', '9:16'],
          audioToggle: true,
        },
      },
      {
        mode: 'i2v',
        falModelId: 'fal-ai/veo3.1/image-to-video',
        ui: {
          modes: ['i2v'],
          duration: { options: ['8s'], default: '8s' },
          resolution: ['720p', '1080p', '4k'],
          aspectRatio: ['16:9', '9:16'],
          audioToggle: true,
          acceptsImageFormats: ['jpg', 'jpeg', 'png'],
          maxUploadMB: 20,
          notes: 'Animate a single still while keeping the prompt and optional native audio aligned to one source image.',
        },
      },
      {
        mode: 'ref2v',
        falModelId: 'fal-ai/veo3.1/reference-to-video',
        ui: {
          modes: ['ref2v'],
          duration: { options: ['8s'], default: '8s' },
          resolution: ['720p', '1080p', '4k'],
          aspectRatio: ['16:9', '9:16'],
          audioToggle: true,
          acceptsImageFormats: ['jpg', 'jpeg', 'png'],
          maxUploadMB: 20,
          notes: 'Attach multiple stills to preserve identity, styling, and wardrobe across the full shot.',
        },
      },
      {
        mode: 'fl2v',
        falModelId: 'fal-ai/veo3.1/first-last-frame-to-video',
        ui: {
          modes: ['fl2v'],
          duration: { options: ['4s', '6s', '8s'], default: '8s' },
          resolution: ['720p', '1080p', '4k'],
          aspectRatio: ['16:9', '9:16'],
          audioToggle: true,
          acceptsImageFormats: ['jpg', 'jpeg', 'png'],
          maxUploadMB: 20,
          notes: 'Bridge two keyframes with Veo 3.1 while the prompt defines motion, pacing, and camera path.',
        },
      },
      {
        mode: 'extend',
        falModelId: 'fal-ai/veo3.1/extend-video',
        ui: {
          modes: ['extend'],
          duration: { options: ['7s'], default: '7s' },
          resolution: ['720p', '1080p', '4k'],
          aspectRatio: ['16:9', '9:16'],
          maxUploadMB: 30,
          audioToggle: true,
          notes: 'Extend an existing Veo-generated MP4 by 7 seconds on the Google direct route, including 4K when selected.',
        },
      },
    ],
    defaultFalModelId: 'fal-ai/veo3.1',
    seo: {
      title: 'Veo 3.1 – Text, Start Image, References & Extend Video',
      description:
        'Generate cinematic Veo 3.1 videos with text prompts, start-image animation, multi-reference guidance, optional last-frame control, and extend workflows in one unified MaxVideoAI model page.',
      canonicalPath: '/models/veo-3-1',
    },
    type: 'Text, start image, references, last frame, extend',
    seoText:
      'Veo 3.1 on MaxVideoAI unifies text prompts, single start-image animation, multi-reference guidance, optional last-frame control, and video extension in one coherent workflow with optional native audio.',
    demoUrl: 'https://media.maxvideoai.com/renders/marketing/24eb7037-bfd1-4f18-bdfa-be98c5dc46d7.mp4',
    media: {
      videoUrl: 'https://media.maxvideoai.com/renders/marketing/f9711b1e-53d5-4a1d-9adf-8186784538e3.mp4',
      imagePath: '/hero/veo-3-1-hero.jpg',
      altText: 'Demo video generated with Veo 3.1',
    },
    prompts: [
      {
        title: 'Scripted hero read',
        prompt: 'Two person street interview in New York City.\nSample dialogue:\nHost: “Did you hear the news?”\nPerson: “Yes, Veo 3.1 text-to-video just landed inside MaxVideoAI.”\nCinematic handheld camera, rich ambient audio, confident VO tone.',
        mode: 't2v',
      },
      {
        title: 'Reference fidelity shot',
        prompt: 'Eight second tracking shot of the hero walking through neon city streets, maintain wardrobe and face from reference stills, cinematic lighting',
        mode: 'ref2v',
        notes: 'Attach 1 to 3 stills via Reference images to lock identity.',
      },
      {
        title: 'First to last bridge',
        prompt: 'Bridge from a glossy studio beauty shot to a warm lifestyle table scene in one fluid motion, preserve product silhouette and reflections, optional narrator line.',
        mode: 'fl2v',
        notes: 'Upload the opening and closing frames to steer the transition precisely.',
      },
    ],
    faqs: [
      {
        question: 'Does Veo 3 ship with the latest motion tuning?',
        answer: 'Yes. MaxVideoAI syncs routing with Google DeepMind updates so motion tuning stays current without manual work.',
      },
      {
        question: 'Can I use more than one image with Veo 3.1?',
        answer:
          'Yes. Use Reference mode for multiple stills, Generate Video with a single start image, or add a Last frame when you need to steer the ending.',
      },
    ],
    pricingHint: {
      currency: 'USD',
      amountCents: 440,
      durationSeconds: 8,
      resolution: '1080p',
    },
  },
];
